// Mocks generated by Mockito 5.4.6 from annotations
// in fitquest/test/add_food_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:fitquest/services/app_state.dart' as _i3;
import 'package:fitquest/services/database_helper.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfile_1 extends _i1.SmartFake implements _i3.UserProfile {
  _FakeUserProfile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppState].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppState extends _i1.Mock implements _i3.AppState {
  MockAppState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  int get calorieGoal =>
      (super.noSuchMethod(Invocation.getter(#calorieGoal), returnValue: 0)
          as int);

  @override
  int get proteinGoal =>
      (super.noSuchMethod(Invocation.getter(#proteinGoal), returnValue: 0)
          as int);

  @override
  int get carbsGoal =>
      (super.noSuchMethod(Invocation.getter(#carbsGoal), returnValue: 0)
          as int);

  @override
  int get fatGoal =>
      (super.noSuchMethod(Invocation.getter(#fatGoal), returnValue: 0) as int);

  @override
  int get fiberGoal =>
      (super.noSuchMethod(Invocation.getter(#fiberGoal), returnValue: 0)
          as int);

  @override
  int get waterGoal =>
      (super.noSuchMethod(Invocation.getter(#waterGoal), returnValue: 0)
          as int);

  @override
  int get steps =>
      (super.noSuchMethod(Invocation.getter(#steps), returnValue: 0) as int);

  @override
  List<_i3.FoodItem> get foods =>
      (super.noSuchMethod(
            Invocation.getter(#foods),
            returnValue: <_i3.FoodItem>[],
          )
          as List<_i3.FoodItem>);

  @override
  List<_i3.Exercise> get exercises =>
      (super.noSuchMethod(
            Invocation.getter(#exercises),
            returnValue: <_i3.Exercise>[],
          )
          as List<_i3.Exercise>);

  @override
  List<_i3.SleepSession> get sleepSessions =>
      (super.noSuchMethod(
            Invocation.getter(#sleepSessions),
            returnValue: <_i3.SleepSession>[],
          )
          as List<_i3.SleepSession>);

  @override
  _i3.UserProfile get profile =>
      (super.noSuchMethod(
            Invocation.getter(#profile),
            returnValue: _FakeUserProfile_1(this, Invocation.getter(#profile)),
          )
          as _i3.UserProfile);

  @override
  int get waterIntake =>
      (super.noSuchMethod(Invocation.getter(#waterIntake), returnValue: 0)
          as int);

  @override
  int get todayCalories =>
      (super.noSuchMethod(Invocation.getter(#todayCalories), returnValue: 0)
          as int);

  @override
  int get todayProtein =>
      (super.noSuchMethod(Invocation.getter(#todayProtein), returnValue: 0)
          as int);

  @override
  int get todayCarbs =>
      (super.noSuchMethod(Invocation.getter(#todayCarbs), returnValue: 0)
          as int);

  @override
  int get todayFat =>
      (super.noSuchMethod(Invocation.getter(#todayFat), returnValue: 0) as int);

  @override
  int get todayFiber =>
      (super.noSuchMethod(Invocation.getter(#todayFiber), returnValue: 0)
          as int);

  @override
  int get todayExerciseCalories =>
      (super.noSuchMethod(
            Invocation.getter(#todayExerciseCalories),
            returnValue: 0,
          )
          as int);

  @override
  int get todayActiveMinutes =>
      (super.noSuchMethod(
            Invocation.getter(#todayActiveMinutes),
            returnValue: 0,
          )
          as int);

  @override
  set dbHelper(_i2.DatabaseHelper? value) => super.noSuchMethod(
    Invocation.setter(#dbHelper, value),
    returnValueForMissingStub: null,
  );

  @override
  set calorieGoal(int? value) => super.noSuchMethod(
    Invocation.setter(#calorieGoal, value),
    returnValueForMissingStub: null,
  );

  @override
  set proteinGoal(int? value) => super.noSuchMethod(
    Invocation.setter(#proteinGoal, value),
    returnValueForMissingStub: null,
  );

  @override
  set carbsGoal(int? value) => super.noSuchMethod(
    Invocation.setter(#carbsGoal, value),
    returnValueForMissingStub: null,
  );

  @override
  set fatGoal(int? value) => super.noSuchMethod(
    Invocation.setter(#fatGoal, value),
    returnValueForMissingStub: null,
  );

  @override
  set fiberGoal(int? value) => super.noSuchMethod(
    Invocation.setter(#fiberGoal, value),
    returnValueForMissingStub: null,
  );

  @override
  set waterGoal(int? value) => super.noSuchMethod(
    Invocation.setter(#waterGoal, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> setTodaySteps(int? steps) =>
      (super.noSuchMethod(
            Invocation.method(#setTodaySteps, [steps]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addFood(_i3.FoodItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#addFood, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFood(_i3.FoodItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#removeFood, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateFood(_i3.FoodItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateFood, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addExercise(_i3.Exercise? item) =>
      (super.noSuchMethod(
            Invocation.method(#addExercise, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeExercise(_i3.Exercise? item) =>
      (super.noSuchMethod(
            Invocation.method(#removeExercise, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addSleep(_i3.SleepSession? sleep) =>
      (super.noSuchMethod(
            Invocation.method(#addSleep, [sleep]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateSleep(_i3.SleepSession? sleep) =>
      (super.noSuchMethod(
            Invocation.method(#updateSleep, [sleep]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeSleep(_i3.SleepSession? sleep) =>
      (super.noSuchMethod(
            Invocation.method(#removeSleep, [sleep]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateProfile(_i3.UserProfile? p) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [p]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addWater(int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#addWater, [amount]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeWater(int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#removeWater, [amount]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
