// Mocks generated by Mockito 5.4.6 from annotations
// in fitquest/test/app_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fitquest/services/app_state.dart' as _i5;
import 'package:fitquest/services/database_helper.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i3.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<int> addFood(_i5.FoodItem? food) =>
      (super.noSuchMethod(
            Invocation.method(#addFood, [food]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.FoodItem>> getFoodLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodLogs, []),
            returnValue: _i4.Future<List<_i5.FoodItem>>.value(<_i5.FoodItem>[]),
          )
          as _i4.Future<List<_i5.FoodItem>>);

  @override
  _i4.Future<int> removeFood(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeFood, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateFood(_i5.FoodItem? food) =>
      (super.noSuchMethod(
            Invocation.method(#updateFood, [food]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> addSleep(_i5.SleepSession? sleep) =>
      (super.noSuchMethod(
            Invocation.method(#addSleep, [sleep]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.SleepSession>> getSleepSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getSleepSessions, []),
            returnValue: _i4.Future<List<_i5.SleepSession>>.value(
              <_i5.SleepSession>[],
            ),
          )
          as _i4.Future<List<_i5.SleepSession>>);

  @override
  _i4.Future<int> removeSleep(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeSleep, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateSleep(_i5.SleepSession? sleep) =>
      (super.noSuchMethod(
            Invocation.method(#updateSleep, [sleep]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> addWater(int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#addWater, [amount]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getWaterIntake() =>
      (super.noSuchMethod(
            Invocation.method(#getWaterIntake, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> removeWater(int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#removeWater, [amount]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> addExercise(_i5.Exercise? exercise) =>
      (super.noSuchMethod(
            Invocation.method(#addExercise, [exercise]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.Exercise>> getExerciseLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseLogs, []),
            returnValue: _i4.Future<List<_i5.Exercise>>.value(<_i5.Exercise>[]),
          )
          as _i4.Future<List<_i5.Exercise>>);

  @override
  _i4.Future<int> removeExercise(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeExercise, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> saveProfile(_i5.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#saveProfile, [profile]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<_i5.UserProfile?> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i4.Future<_i5.UserProfile?>.value(),
          )
          as _i4.Future<_i5.UserProfile?>);

  @override
  _i4.Future<int> saveGoals(Map<String, int>? goals) =>
      (super.noSuchMethod(
            Invocation.method(#saveGoals, [goals]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<Map<String, dynamic>> getGoals() =>
      (super.noSuchMethod(
            Invocation.method(#getGoals, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<int> setTodaySteps(int? steps) =>
      (super.noSuchMethod(
            Invocation.method(#setTodaySteps, [steps]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getTodaySteps() =>
      (super.noSuchMethod(
            Invocation.method(#getTodaySteps, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<dynamic> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);
}
