export interface Exercise {
  id: string;
  name: string;
  category: 'gym' | 'home' | 'yoga' | 'cardio' | 'sports' | 'strength' | 'flexibility' | 'hiit' | 'pilates' | 'dance' | 'martial-arts';
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  equipment: string[];
  muscleGroups: string[];
  caloriesPerMinute: number;
  description: string;
  instructions: string[];
  tips: string[];
  sets?: number;
  reps?: string;
  duration?: number;
}

export const exerciseLibrary: Exercise[] = [
  // GYM EXERCISES
  { id: 'ex1', name: 'Barbell Bench Press', category: 'gym', difficulty: 'intermediate', equipment: ['Barbell', 'Bench'], muscleGroups: ['Chest', 'Triceps', 'Shoulders'], caloriesPerMinute: 8, description: 'Classic compound chest exercise', instructions: ['Lie flat on bench with feet on floor', 'Grip bar slightly wider than shoulders', 'Lower bar to chest, keeping elbows at 45 degrees', 'Press bar up explosively', 'Lock out arms at top'], tips: ['Keep shoulder blades retracted', 'Maintain arch in lower back', 'Control the descent'], sets: 4, reps: '8-12' },
  { id: 'ex2', name: 'Barbell Squat', category: 'gym', difficulty: 'intermediate', equipment: ['Barbell', 'Squat Rack'], muscleGroups: ['Quads', 'Glutes', 'Hamstrings', 'Core'], caloriesPerMinute: 10, description: 'King of leg exercises', instructions: ['Position bar on upper back', 'Feet shoulder-width apart', 'Break at hips and knees simultaneously', 'Descend until thighs parallel to ground', 'Drive through heels to stand'], tips: ['Keep chest up', 'Knees track over toes', 'Breathe out on way up'], sets: 4, reps: '6-10' },
  { id: 'ex3', name: 'Deadlift', category: 'gym', difficulty: 'advanced', equipment: ['Barbell'], muscleGroups: ['Back', 'Glutes', 'Hamstrings', 'Core'], caloriesPerMinute: 12, description: 'Full body power exercise', instructions: ['Stand with feet hip-width apart', 'Grip bar just outside knees', 'Keep back neutral, chest up', 'Drive through heels, extend hips and knees', 'Stand fully upright'], tips: ['Engage lats throughout', 'Bar stays close to body', 'Lock out hips and knees together'], sets: 3, reps: '5-8' },
  { id: 'ex4', name: 'Pull-ups', category: 'gym', difficulty: 'intermediate', equipment: ['Pull-up Bar'], muscleGroups: ['Lats', 'Biceps', 'Upper Back'], caloriesPerMinute: 9, description: 'Upper body pulling exercise', instructions: ['Hang from bar with arms fully extended', 'Pull body up until chin over bar', 'Lower with control', 'Repeat'], tips: ['Avoid swinging', 'Engage core', 'Full range of motion'], sets: 4, reps: '8-12' },
  { id: 'ex5', name: 'Overhead Press', category: 'gym', difficulty: 'intermediate', equipment: ['Barbell'], muscleGroups: ['Shoulders', 'Triceps', 'Core'], caloriesPerMinute: 7, description: 'Primary shoulder builder', instructions: ['Stand with feet shoulder-width', 'Bar at collar bone level', 'Press bar overhead', 'Lock out arms', 'Lower with control'], tips: ['Keep core tight', 'Bar path straight up', 'No excessive back arch'], sets: 4, reps: '8-10' },
  
  // HOME WORKOUT
  { id: 'ex6', name: 'Push-ups', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Chest', 'Triceps', 'Shoulders'], caloriesPerMinute: 7, description: 'Classic bodyweight chest exercise', instructions: ['Start in plank position', 'Lower body until chest near floor', 'Push back up', 'Keep body straight'], tips: ['Engage core', 'Elbows at 45 degrees', 'Full range of motion'], sets: 3, reps: '15-20' },
  { id: 'ex7', name: 'Bodyweight Squats', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Quads', 'Glutes', 'Hamstrings'], caloriesPerMinute: 6, description: 'Fundamental leg exercise', instructions: ['Stand with feet shoulder-width', 'Lower hips back and down', 'Keep chest up', 'Descend until thighs parallel', 'Stand back up'], tips: ['Weight on heels', 'Knees over toes', 'Breathe steadily'], sets: 3, reps: '20-25' },
  { id: 'ex8', name: 'Lunges', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Quads', 'Glutes', 'Hamstrings'], caloriesPerMinute: 6, description: 'Unilateral leg exercise', instructions: ['Step forward with one leg', 'Lower hips until both knees at 90 degrees', 'Push back to start', 'Alternate legs'], tips: ['Keep torso upright', 'Front knee over ankle', 'Control the movement'], sets: 3, reps: '12-15 each leg' },
  { id: 'ex9', name: 'Plank', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Core', 'Shoulders'], caloriesPerMinute: 4, description: 'Core stability exercise', instructions: ['Forearms on ground, elbows under shoulders', 'Extend legs behind you', 'Keep body in straight line', 'Hold position'], tips: ['Squeeze glutes', 'Don\'t sag hips', 'Breathe normally'], duration: 60 },
  { id: 'ex10', name: 'Mountain Climbers', category: 'home', difficulty: 'intermediate', equipment: [], muscleGroups: ['Core', 'Shoulders', 'Legs'], caloriesPerMinute: 10, description: 'Dynamic core and cardio exercise', instructions: ['Start in push-up position', 'Drive one knee toward chest', 'Quickly switch legs', 'Continue alternating'], tips: ['Keep hips level', 'Maintain plank position', 'Quick tempo'], sets: 3, reps: '30 seconds' },
  
  // YOGA
  { id: 'ex11', name: 'Surya Namaskar (Sun Salutation)', category: 'yoga', difficulty: 'beginner', equipment: ['Yoga Mat'], muscleGroups: ['Full Body'], caloriesPerMinute: 4, description: 'Complete yoga sequence', instructions: ['Start in prayer pose', 'Raise arms overhead', 'Forward fold', 'Plank to chaturanga', 'Upward dog', 'Downward dog', 'Jump forward', 'Stand and repeat'], tips: ['Synchronize with breath', 'Move slowly and mindfully', 'One breath per movement'], sets: 5, reps: '1 round' },
  { id: 'ex12', name: 'Vrikshasana (Tree Pose)', category: 'yoga', difficulty: 'beginner', equipment: ['Yoga Mat'], muscleGroups: ['Legs', 'Core'], caloriesPerMinute: 3, description: 'Balance and focus pose', instructions: ['Stand on one leg', 'Place other foot on inner thigh', 'Bring hands to prayer position', 'Focus on a fixed point', 'Hold for 30-60 seconds'], tips: ['Keep standing leg strong', 'Engage core for balance', 'Breathe deeply'], duration: 60 },
  { id: 'ex13', name: 'Bhujangasana (Cobra Pose)', category: 'yoga', difficulty: 'beginner', equipment: ['Yoga Mat'], muscleGroups: ['Back', 'Core'], caloriesPerMinute: 3, description: 'Backbend for spine flexibility', instructions: ['Lie face down', 'Hands under shoulders', 'Press upper body up', 'Keep hips on ground', 'Look upward'], tips: ['Engage back muscles', 'Don\'t over-compress lower back', 'Shoulders away from ears'], duration: 30 },
  { id: 'ex14', name: 'Adho Mukha Svanasana (Downward Dog)', category: 'yoga', difficulty: 'beginner', equipment: ['Yoga Mat'], muscleGroups: ['Shoulders', 'Hamstrings', 'Calves'], caloriesPerMinute: 4, description: 'Foundational yoga pose', instructions: ['Start on hands and knees', 'Lift hips up and back', 'Straighten legs', 'Press heels toward floor', 'Head between arms'], tips: ['Spread fingers wide', 'Rotate shoulders outward', 'Relax neck'], duration: 60 },
  { id: 'ex15', name: 'Warrior I (Virabhadrasana I)', category: 'yoga', difficulty: 'beginner', equipment: ['Yoga Mat'], muscleGroups: ['Legs', 'Core', 'Shoulders'], caloriesPerMinute: 4, description: 'Standing strength pose', instructions: ['Lunge position', 'Back foot at 45 degrees', 'Front knee over ankle', 'Arms raised overhead', 'Square hips forward'], tips: ['Ground through both feet', 'Engage core', 'Reach up through fingertips'], duration: 45 },
  
  // CARDIO
  { id: 'ex16', name: 'Burpees', category: 'cardio', difficulty: 'intermediate', equipment: [], muscleGroups: ['Full Body'], caloriesPerMinute: 12, description: 'High-intensity full body exercise', instructions: ['Start standing', 'Drop to plank position', 'Do a push-up', 'Jump feet to hands', 'Jump up explosively'], tips: ['Land softly', 'Keep core engaged', 'Maintain pace'], sets: 3, reps: '10-15' },
  { id: 'ex17', name: 'Jumping Jacks', category: 'cardio', difficulty: 'beginner', equipment: [], muscleGroups: ['Full Body'], caloriesPerMinute: 8, description: 'Classic cardio warm-up', instructions: ['Start with feet together', 'Jump feet apart while raising arms', 'Jump back to start', 'Repeat continuously'], tips: ['Land on balls of feet', 'Keep steady rhythm', 'Breathe regularly'], sets: 3, reps: '30 seconds' },
  { id: 'ex18', name: 'High Knees', category: 'cardio', difficulty: 'beginner', equipment: [], muscleGroups: ['Legs', 'Core'], caloriesPerMinute: 10, description: 'Running in place with high knee lift', instructions: ['Run in place', 'Drive knees up to waist level', 'Pump arms', 'Quick tempo'], tips: ['Stay on balls of feet', 'Lean slightly forward', 'Fast turnover'], sets: 3, reps: '30 seconds' },
  { id: 'ex19', name: 'Jump Rope', category: 'cardio', difficulty: 'beginner', equipment: ['Jump Rope'], muscleGroups: ['Calves', 'Shoulders'], caloriesPerMinute: 11, description: 'Classic cardio exercise', instructions: ['Hold rope handles', 'Swing rope overhead', 'Jump as rope passes under feet', 'Land softly'], tips: ['Use wrists not arms', 'Small jumps', 'Stay on toes'], duration: 180 },
  { id: 'ex20', name: 'Box Jumps', category: 'cardio', difficulty: 'intermediate', equipment: ['Plyo Box'], muscleGroups: ['Legs', 'Glutes'], caloriesPerMinute: 11, description: 'Explosive leg power exercise', instructions: ['Stand facing box', 'Swing arms and jump onto box', 'Land softly with knees bent', 'Step down', 'Repeat'], tips: ['Start with lower box', 'Full hip extension', 'Soft landing'], sets: 3, reps: '8-12' },

  // MORE GYM EXERCISES
  { id: 'ex21', name: 'Dumbbell Rows', category: 'gym', difficulty: 'beginner', equipment: ['Dumbbells', 'Bench'], muscleGroups: ['Back', 'Biceps'], caloriesPerMinute: 6, description: 'Unilateral back exercise', instructions: ['Place one knee on bench', 'Row dumbbell to hip', 'Lower with control', 'Keep back flat'], tips: ['Pull with elbow not hand', 'Squeeze shoulder blade', 'No rotation'], sets: 4, reps: '10-12 each' },
  { id: 'ex22', name: 'Leg Press', category: 'gym', difficulty: 'beginner', equipment: ['Leg Press Machine'], muscleGroups: ['Quads', 'Glutes'], caloriesPerMinute: 7, description: 'Leg strength builder', instructions: ['Sit in machine', 'Feet shoulder-width on platform', 'Lower weight with control', 'Press back up'], tips: ['Full range of motion', 'Don\'t lock knees', 'Keep lower back pressed'], sets: 4, reps: '12-15' },
  { id: 'ex23', name: 'Lat Pulldown', category: 'gym', difficulty: 'beginner', equipment: ['Cable Machine'], muscleGroups: ['Lats', 'Biceps'], caloriesPerMinute: 6, description: 'Back width exercise', instructions: ['Sit at machine', 'Grip bar wider than shoulders', 'Pull bar to upper chest', 'Squeeze shoulder blades', 'Return with control'], tips: ['Lean back slightly', 'Pull elbows down and back', 'Chest out'], sets: 4, reps: '10-12' },
  { id: 'ex24', name: 'Bicep Curls', category: 'gym', difficulty: 'beginner', equipment: ['Dumbbells'], muscleGroups: ['Biceps'], caloriesPerMinute: 4, description: 'Isolation exercise for biceps', instructions: ['Stand with dumbbells at sides', 'Curl weights up', 'Keep elbows stationary', 'Lower with control'], tips: ['No swinging', 'Squeeze at top', 'Control eccentric'], sets: 3, reps: '12-15' },
  { id: 'ex25', name: 'Tricep Dips', category: 'gym', difficulty: 'intermediate', equipment: ['Dip Station'], muscleGroups: ['Triceps', 'Chest', 'Shoulders'], caloriesPerMinute: 7, description: 'Compound tricep exercise', instructions: ['Grip bars, support body', 'Lower body by bending elbows', 'Go until 90-degree angle', 'Press back up'], tips: ['Keep elbows in', 'Lean forward for chest', 'Upright for triceps'], sets: 3, reps: '8-12' },
  
  // MORE HOME EXERCISES
  { id: 'ex26', name: 'Glute Bridges', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Glutes', 'Hamstrings'], caloriesPerMinute: 5, description: 'Hip extension exercise', instructions: ['Lie on back, knees bent', 'Feet flat on floor', 'Lift hips up', 'Squeeze glutes at top', 'Lower down'], tips: ['Drive through heels', 'Don\'t overarch back', 'Hold at top'], sets: 3, reps: '15-20' },
  { id: 'ex27', name: 'Wall Sit', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Quads', 'Glutes'], caloriesPerMinute: 6, description: 'Isometric leg exercise', instructions: ['Back against wall', 'Slide down to 90-degree angle', 'Hold position', 'Keep weight in heels'], tips: ['Thighs parallel to floor', 'Back flat on wall', 'Breathe steadily'], duration: 60 },
  { id: 'ex28', name: 'Superman', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Lower Back', 'Glutes'], caloriesPerMinute: 4, description: 'Lower back strengthener', instructions: ['Lie face down', 'Extend arms forward', 'Lift arms and legs simultaneously', 'Hold briefly', 'Lower down'], tips: ['Look down to protect neck', 'Squeeze glutes', 'Controlled movement'], sets: 3, reps: '12-15' },
  { id: 'ex29', name: 'Tricep Dips (Chair)', category: 'home', difficulty: 'beginner', equipment: ['Chair'], muscleGroups: ['Triceps', 'Shoulders'], caloriesPerMinute: 5, description: 'Home tricep exercise', instructions: ['Hands on chair edge', 'Legs extended forward', 'Lower body by bending elbows', 'Press back up'], tips: ['Elbows back not out', 'Keep hips close to chair', 'Shoulders down'], sets: 3, reps: '10-15' },
  { id: 'ex30', name: 'Bicycle Crunches', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Abs', 'Obliques'], caloriesPerMinute: 6, description: 'Dynamic ab exercise', instructions: ['Lie on back, hands behind head', 'Lift shoulders off ground', 'Bring elbow to opposite knee', 'Alternate sides'], tips: ['Twist from core', 'Don\'t pull on neck', 'Keep lower back down'], sets: 3, reps: '20-30' },
  
  // MORE YOGA
  { id: 'ex31', name: 'Warrior II (Virabhadrasana II)', category: 'yoga', difficulty: 'beginner', equipment: ['Yoga Mat'], muscleGroups: ['Legs', 'Shoulders'], caloriesPerMinute: 4, description: 'Strong standing pose', instructions: ['Wide stance', 'Front knee bent 90 degrees', 'Arms extended parallel to floor', 'Gaze over front hand'], tips: ['Back leg straight', 'Square hips to side', 'Shoulders over hips'], duration: 45 },
  { id: 'ex32', name: 'Triangle Pose (Trikonasana)', category: 'yoga', difficulty: 'beginner', equipment: ['Yoga Mat'], muscleGroups: ['Legs', 'Core', 'Shoulders'], caloriesPerMinute: 3, description: 'Standing stretch and strength pose', instructions: ['Wide stance, feet parallel', 'Extend to side', 'Lower hand to shin or floor', 'Top arm reaches up', 'Look up at hand'], tips: ['Keep both legs straight', 'Open chest', 'Engage core'], duration: 45 },
  { id: 'ex33', name: 'Child\'s Pose (Balasana)', category: 'yoga', difficulty: 'beginner', equipment: ['Yoga Mat'], muscleGroups: ['Back', 'Hips'], caloriesPerMinute: 2, description: 'Resting and recovery pose', instructions: ['Kneel on mat', 'Sit back on heels', 'Extend arms forward', 'Forehead to mat', 'Breathe deeply'], tips: ['Relax completely', 'Widen knees if needed', 'Focus on breath'], duration: 60 },
  { id: 'ex34', name: 'Pigeon Pose (Kapotasana)', category: 'yoga', difficulty: 'intermediate', equipment: ['Yoga Mat'], muscleGroups: ['Hips', 'Glutes'], caloriesPerMinute: 3, description: 'Deep hip opener', instructions: ['From downward dog', 'Bring knee forward between hands', 'Extend back leg', 'Lower hips to floor', 'Fold forward if able'], tips: ['Keep hips square', 'Support with props if needed', 'Breathe into stretch'], duration: 90 },
  { id: 'ex35', name: 'Cat-Cow Stretch (Marjaryasana-Bitilasana)', category: 'yoga', difficulty: 'beginner', equipment: ['Yoga Mat'], muscleGroups: ['Spine', 'Core'], caloriesPerMinute: 3, description: 'Spinal mobility flow', instructions: ['Start on hands and knees', 'Inhale: arch back, look up', 'Exhale: round spine, tuck chin', 'Flow between positions'], tips: ['Move with breath', 'Engage whole spine', 'No strain'], sets: 1, reps: '10 rounds' },
  
  // HIIT EXERCISES
  { id: 'ex36', name: 'Squat Jumps', category: 'hiit', difficulty: 'intermediate', equipment: [], muscleGroups: ['Legs', 'Glutes'], caloriesPerMinute: 11, description: 'Explosive lower body exercise', instructions: ['Squat down', 'Explode up into jump', 'Land softly', 'Immediately repeat'], tips: ['Full hip extension', 'Soft landing', 'Quick turnaround'], sets: 4, reps: '12-15' },
  { id: 'ex37', name: 'Plank Jacks', category: 'hiit', difficulty: 'intermediate', equipment: [], muscleGroups: ['Core', 'Shoulders'], caloriesPerMinute: 9, description: 'Dynamic plank variation', instructions: ['Start in plank position', 'Jump feet apart', 'Jump back together', 'Maintain plank form'], tips: ['Keep hips level', 'Engage core', 'Quick tempo'], sets: 3, reps: '30 seconds' },
  { id: 'ex38', name: 'Tuck Jumps', category: 'hiit', difficulty: 'advanced', equipment: [], muscleGroups: ['Legs', 'Core'], caloriesPerMinute: 13, description: 'High-intensity plyometric exercise', instructions: ['Jump explosively', 'Bring knees to chest', 'Land softly', 'Immediately repeat'], tips: ['Maximum height', 'Quick ground contact', 'Land on balls of feet'], sets: 3, reps: '8-10' },
  { id: 'ex39', name: 'Battle Ropes', category: 'hiit', difficulty: 'intermediate', equipment: ['Battle Ropes'], muscleGroups: ['Shoulders', 'Core', 'Arms'], caloriesPerMinute: 12, description: 'Full body conditioning', instructions: ['Hold rope ends', 'Create waves by moving arms', 'Maintain athletic stance', 'Keep intensity high'], tips: ['Engage core', 'Slight knee bend', 'Breathe steadily'], sets: 4, reps: '30 seconds' },
  { id: 'ex40', name: 'Skater Jumps', category: 'hiit', difficulty: 'intermediate', equipment: [], muscleGroups: ['Legs', 'Glutes', 'Core'], caloriesPerMinute: 10, description: 'Lateral power exercise', instructions: ['Leap to side landing on one foot', 'Touch opposite hand to ground', 'Explosively leap to other side', 'Alternate continuously'], tips: ['Push off powerfully', 'Soft landing', 'Maintain balance'], sets: 3, reps: '20-30' },
  
  // SPORTS SPECIFIC
  { id: 'ex41', name: 'Cricket Bowling Practice', category: 'sports', difficulty: 'intermediate', equipment: ['Cricket Ball'], muscleGroups: ['Shoulders', 'Core', 'Legs'], caloriesPerMinute: 7, description: 'Cricket bowling technique', instructions: ['Start with run-up', 'Build momentum', 'Load back leg', 'Release ball with arm rotation', 'Follow through'], tips: ['Smooth run-up', 'Stay side-on', 'High arm action'], duration: 180 },
  { id: 'ex42', name: 'Cricket Batting Drills', category: 'sports', difficulty: 'intermediate', equipment: ['Cricket Bat', 'Ball'], muscleGroups: ['Arms', 'Core', 'Legs'], caloriesPerMinute: 6, description: 'Batting practice', instructions: ['Proper stance', 'Watch the ball', 'Execute shot', 'Follow through', 'Return to stance'], tips: ['Balance on back foot', 'Head still', 'Play with straight bat'], duration: 300 },
  { id: 'ex43', name: 'Shuttle Run', category: 'sports', difficulty: 'beginner', equipment: ['Cones'], muscleGroups: ['Legs', 'Cardio'], caloriesPerMinute: 10, description: 'Agility and speed drill', instructions: ['Set up two markers', 'Sprint between them', 'Touch each marker', 'Quick direction changes'], tips: ['Low center of gravity', 'Quick feet', 'Explosive starts'], sets: 5, reps: '30 seconds' },
  { id: 'ex44', name: 'Badminton Footwork', category: 'sports', difficulty: 'intermediate', equipment: ['Badminton Court'], muscleGroups: ['Legs', 'Cardio'], caloriesPerMinute: 8, description: 'Court movement practice', instructions: ['Start at center', 'Move to corners', 'Return to center', 'Quick recovery steps'], tips: ['Stay on toes', 'Low stance', 'Quick returns'], duration: 300 },
  { id: 'ex45', name: 'Football Dribbling', category: 'sports', difficulty: 'intermediate', equipment: ['Football', 'Cones'], muscleGroups: ['Legs', 'Core'], caloriesPerMinute: 7, description: 'Ball control practice', instructions: ['Set up cone course', 'Dribble through cones', 'Close ball control', 'Both feet practice'], tips: ['Keep ball close', 'Look up periodically', 'Use both feet'], duration: 300 },
  
  // STRENGTH TRAINING
  { id: 'ex46', name: 'Romanian Deadlift', category: 'gym', difficulty: 'intermediate', equipment: ['Barbell'], muscleGroups: ['Hamstrings', 'Glutes', 'Lower Back'], caloriesPerMinute: 8, description: 'Hamstring focused deadlift', instructions: ['Stand holding barbell', 'Slight knee bend', 'Hinge at hips', 'Lower bar along legs', 'Return to standing'], tips: ['Keep back straight', 'Feel hamstring stretch', 'Don\'t round back'], sets: 4, reps: '8-12' },
  { id: 'ex47', name: 'Front Squat', category: 'gym', difficulty: 'advanced', equipment: ['Barbell'], muscleGroups: ['Quads', 'Core'], caloriesPerMinute: 10, description: 'Quad-focused squat variation', instructions: ['Bar on front shoulders', 'Elbows high', 'Squat down keeping torso upright', 'Drive up'], tips: ['Elbows up throughout', 'Chest up', 'Maintain upright posture'], sets: 4, reps: '6-10' },
  { id: 'ex48', name: 'Face Pulls', category: 'gym', difficulty: 'beginner', equipment: ['Cable Machine'], muscleGroups: ['Rear Delts', 'Upper Back'], caloriesPerMinute: 5, description: 'Shoulder health exercise', instructions: ['Set cable at face height', 'Pull rope to face', 'Separate hands at face', 'Return slowly'], tips: ['Keep elbows high', 'Pull apart at end', 'Squeeze shoulder blades'], sets: 3, reps: '15-20' },
  { id: 'ex49', name: 'Cable Flyes', category: 'gym', difficulty: 'beginner', equipment: ['Cable Machine'], muscleGroups: ['Chest'], caloriesPerMinute: 5, description: 'Chest isolation exercise', instructions: ['Stand between cables', 'Arms extended to sides', 'Bring hands together in front', 'Return with control'], tips: ['Slight elbow bend', 'Feel chest stretch', 'Squeeze at center'], sets: 3, reps: '12-15' },
  { id: 'ex50', name: 'Farmers Walk', category: 'gym', difficulty: 'beginner', equipment: ['Dumbbells/Kettlebells'], muscleGroups: ['Grip', 'Traps', 'Core'], caloriesPerMinute: 7, description: 'Loaded carry exercise', instructions: ['Hold heavy weights at sides', 'Walk for distance/time', 'Keep posture upright', 'Don\'t shrug shoulders'], tips: ['Tight core', 'Shoulders back', 'Steady breathing'], duration: 60 },

  // MORE HOME EXERCISES
  { id: 'ex51', name: 'Pike Push-ups', category: 'home', difficulty: 'intermediate', equipment: [], muscleGroups: ['Shoulders', 'Triceps'], caloriesPerMinute: 6, description: 'Shoulder-focused push-up', instructions: ['Start in downward dog position', 'Lower head toward floor', 'Push back up', 'Keep hips high'], tips: ['Hips stay high', 'Head between arms', 'Elbows back'], sets: 3, reps: '10-15' },
  { id: 'ex52', name: 'Single Leg Deadlift', category: 'home', difficulty: 'intermediate', equipment: [], muscleGroups: ['Hamstrings', 'Glutes', 'Balance'], caloriesPerMinute: 5, description: 'Unilateral hamstring exercise', instructions: ['Stand on one leg', 'Hinge at hip', 'Extend other leg back', 'Return to standing'], tips: ['Keep back straight', 'Maintain balance', 'Control movement'], sets: 3, reps: '10-12 each' },
  { id: 'ex53', name: 'Diamond Push-ups', category: 'home', difficulty: 'intermediate', equipment: [], muscleGroups: ['Triceps', 'Chest'], caloriesPerMinute: 7, description: 'Tricep-focused push-up', instructions: ['Hands close together forming diamond', 'Lower chest to hands', 'Push back up'], tips: ['Keep elbows in', 'Maintain plank', 'Full range of motion'], sets: 3, reps: '8-12' },
  { id: 'ex54', name: 'Flutter Kicks', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Lower Abs', 'Hip Flexors'], caloriesPerMinute: 5, description: 'Lower ab exercise', instructions: ['Lie on back', 'Lift legs slightly off ground', 'Alternate kicking up and down', 'Keep core engaged'], tips: ['Lower back pressed down', 'Small movements', 'Steady rhythm'], sets: 3, reps: '30 seconds' },
  { id: 'ex55', name: 'Russian Twists', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Obliques', 'Core'], caloriesPerMinute: 6, description: 'Rotational core exercise', instructions: ['Sit with knees bent', 'Lean back slightly', 'Rotate torso side to side', 'Touch floor each side'], tips: ['Lift feet for harder version', 'Control rotation', 'Engage core'], sets: 3, reps: '20-30' },
  
  // MORE YOGA & FLEXIBILITY
  { id: 'ex56', name: 'Seated Forward Fold', category: 'yoga', difficulty: 'beginner', equipment: ['Yoga Mat'], muscleGroups: ['Hamstrings', 'Back'], caloriesPerMinute: 2, description: 'Hamstring and back stretch', instructions: ['Sit with legs extended', 'Hinge at hips', 'Reach for feet', 'Breathe and relax into stretch'], tips: ['Keep back straight', 'Don\'t force', 'Use strap if needed'], duration: 60 },
  { id: 'ex57', name: 'Camel Pose (Ustrasana)', category: 'yoga', difficulty: 'intermediate', equipment: ['Yoga Mat'], muscleGroups: ['Back', 'Chest', 'Hip Flexors'], caloriesPerMinute: 4, description: 'Deep backbend', instructions: ['Kneel with knees hip-width', 'Place hands on lower back', 'Arch back', 'Reach for heels if able'], tips: ['Engage glutes', 'Lead with chest', 'Don\'t drop head back'], duration: 30 },
  { id: 'ex58', name: 'Garland Pose (Malasana)', category: 'yoga', difficulty: 'beginner', equipment: ['Yoga Mat'], muscleGroups: ['Hips', 'Ankles', 'Groin'], caloriesPerMinute: 3, description: 'Deep squat pose', instructions: ['Squat with feet slightly wider than hips', 'Elbows inside knees', 'Hands in prayer', 'Press elbows into knees'], tips: ['Heels down if possible', 'Keep spine long', 'Open hips'], duration: 60 },
  { id: 'ex59', name: 'Bridge Pose (Setu Bandhasana)', category: 'yoga', difficulty: 'beginner', equipment: ['Yoga Mat'], muscleGroups: ['Glutes', 'Hamstrings', 'Back'], caloriesPerMinute: 4, description: 'Gentle backbend', instructions: ['Lie on back, knees bent', 'Feet hip-width', 'Lift hips up', 'Interlace hands under back'], tips: ['Press through heels', 'Engage glutes', 'Lift chest to chin'], duration: 45 },
  { id: 'ex60', name: 'Boat Pose (Navasana)', category: 'yoga', difficulty: 'intermediate', equipment: ['Yoga Mat'], muscleGroups: ['Core', 'Hip Flexors'], caloriesPerMinute: 5, description: 'Core strengthening pose', instructions: ['Sit on mat', 'Lift legs to 45 degrees', 'Extend arms forward', 'Balance on sitting bones', 'Hold'], tips: ['Keep chest lifted', 'Bend knees if needed', 'Breathe steadily'], duration: 30 },
  
  // PILATES
  { id: 'ex61', name: 'The Hundred', category: 'pilates', difficulty: 'beginner', equipment: ['Mat'], muscleGroups: ['Core'], caloriesPerMinute: 5, description: 'Classic Pilates breathing exercise', instructions: ['Lie on back', 'Lift head and legs', 'Pump arms up and down', 'Breathe 5 in, 5 out'], tips: ['Keep lower back down', 'Engage deep core', 'Steady breathing pattern'], sets: 1, reps: '100 pumps' },
  { id: 'ex62', name: 'Roll Up', category: 'pilates', difficulty: 'intermediate', equipment: ['Mat'], muscleGroups: ['Core', 'Back'], caloriesPerMinute: 4, description: 'Spinal articulation exercise', instructions: ['Lie flat, arms overhead', 'Roll up vertebra by vertebra', 'Reach toward toes', 'Roll back down slowly'], tips: ['Control throughout', 'Articulate each vertebra', 'No momentum'], sets: 3, reps: '8-10' },
  { id: 'ex63', name: 'Single Leg Stretch', category: 'pilates', difficulty: 'beginner', equipment: ['Mat'], muscleGroups: ['Core', 'Hip Flexors'], caloriesPerMinute: 5, description: 'Core stability exercise', instructions: ['Lie on back, head lifted', 'One knee to chest, other leg extended', 'Switch legs', 'Maintain core engagement'], tips: ['Keep shoulders off mat', 'Extend fully', 'Smooth transitions'], sets: 3, reps: '10 each leg' },
  { id: 'ex64', name: 'Swimming', category: 'pilates', difficulty: 'intermediate', equipment: ['Mat'], muscleGroups: ['Back', 'Glutes', 'Shoulders'], caloriesPerMinute: 6, description: 'Back extension exercise', instructions: ['Lie face down', 'Lift arms, legs, and chest', 'Flutter arms and legs', 'Keep neck neutral'], tips: ['Engage glutes', 'Look down', 'Controlled movement'], sets: 3, reps: '30 seconds' },
  { id: 'ex65', name: 'Pilates Plank', category: 'pilates', difficulty: 'beginner', equipment: ['Mat'], muscleGroups: ['Core', 'Shoulders'], caloriesPerMinute: 5, description: 'Core endurance exercise', instructions: ['Forearm plank position', 'Pull belly button to spine', 'Hold position', 'Breathe naturally'], tips: ['Shoulders over elbows', 'Neutral spine', 'Engage deep core'], duration: 60 },
  
  // DANCE/CARDIO
  { id: 'ex66', name: 'Bollywood Dance Cardio', category: 'dance', difficulty: 'beginner', equipment: [], muscleGroups: ['Full Body'], caloriesPerMinute: 9, description: 'Fun Indian dance workout', instructions: ['Follow choreography', 'Big arm movements', 'Hip isolations', 'Energetic jumps'], tips: ['Have fun', 'Express yourself', 'Keep moving'], duration: 300 },
  { id: 'ex67', name: 'Bhangra Workout', category: 'dance', difficulty: 'beginner', equipment: [], muscleGroups: ['Full Body'], caloriesPerMinute: 10, description: 'Energetic Punjabi dance', instructions: ['High-energy movements', 'Jump and bounce', 'Shoulder shrugs', 'Hand waves'], tips: ['Full commitment', 'Stay light on feet', 'Enjoy the rhythm'], duration: 300 },
  { id: 'ex68', name: 'Zumba', category: 'dance', difficulty: 'beginner', equipment: [], muscleGroups: ['Full Body'], caloriesPerMinute: 9, description: 'Latin-inspired dance fitness', instructions: ['Follow instructor', 'Mix of dance styles', 'Continuous movement', 'Full body engagement'], tips: ['Don\'t worry about perfection', 'Keep moving', 'Have fun'], duration: 300 },
  { id: 'ex69', name: 'Hip Hop Dance', category: 'dance', difficulty: 'intermediate', equipment: [], muscleGroups: ['Full Body'], caloriesPerMinute: 8, description: 'Street dance workout', instructions: ['Learn moves', 'Practice combos', 'Add your style', 'Build confidence'], tips: ['Start slow', 'Add energy gradually', 'Express yourself'], duration: 300 },
  { id: 'ex70', name: 'Step Aerobics', category: 'dance', difficulty: 'beginner', equipment: ['Step Platform'], muscleGroups: ['Legs', 'Cardio'], caloriesPerMinute: 8, description: 'Choreographed stepping routine', instructions: ['Step up and down', 'Follow patterns', 'Add arm movements', 'Keep rhythm'], tips: ['Land heel to toe', 'Stay on beat', 'Watch foot placement'], duration: 300 },

  // MARTIAL ARTS
  { id: 'ex71', name: 'Shadowboxing', category: 'martial-arts', difficulty: 'beginner', equipment: [], muscleGroups: ['Shoulders', 'Core', 'Cardio'], caloriesPerMinute: 9, description: 'Boxing practice without partner', instructions: ['Boxing stance', 'Throw punches in air', 'Mix jabs, crosses, hooks', 'Move around'], tips: ['Keep hands up', 'Rotate hips', 'Stay light on feet'], sets: 3, reps: '3 minutes' },
  { id: 'ex72', name: 'Kickboxing Combos', category: 'martial-arts', difficulty: 'intermediate', equipment: [], muscleGroups: ['Full Body'], caloriesPerMinute: 11, description: 'Punches and kicks combinations', instructions: ['Start in fighting stance', 'Throw punch combinations', 'Add kicks', 'Maintain balance'], tips: ['Chamber kicks properly', 'Return to guard', 'Power from hips'], sets: 3, reps: '3 minutes' },
  { id: 'ex73', name: 'Martial Arts Kicks', category: 'martial-arts', difficulty: 'intermediate', equipment: [], muscleGroups: ['Legs', 'Core', 'Balance'], caloriesPerMinute: 8, description: 'Various kicking techniques', instructions: ['Practice front kicks', 'Side kicks', 'Roundhouse kicks', 'Maintain control'], tips: ['Chamber each kick', 'Extend fully', 'Recover balance'], sets: 3, reps: '10 each leg' },
  { id: 'ex74', name: 'Kata Practice', category: 'martial-arts', difficulty: 'intermediate', equipment: [], muscleGroups: ['Full Body'], caloriesPerMinute: 6, description: 'Martial arts form practice', instructions: ['Perform kata sequence', 'Focus on technique', 'Controlled movements', 'Proper breathing'], tips: ['Quality over speed', 'Sharp techniques', 'Mental focus'], duration: 300 },
  { id: 'ex75', name: 'Punching Bag Work', category: 'martial-arts', difficulty: 'intermediate', equipment: ['Punching Bag'], muscleGroups: ['Shoulders', 'Core', 'Arms'], caloriesPerMinute: 10, description: 'Heavy bag training', instructions: ['Throw combinations', 'Vary power and speed', 'Move around bag', 'Defensive movements'], tips: ['Proper form', 'Don\'t overextend', 'Keep hands up'], sets: 5, reps: '3 minutes' },

  // GYM - ISOLATION
  { id: 'ex76', name: 'Lateral Raises', category: 'gym', difficulty: 'beginner', equipment: ['Dumbbells'], muscleGroups: ['Shoulders'], caloriesPerMinute: 4, description: 'Shoulder width exercise', instructions: ['Stand with dumbbells at sides', 'Raise arms to sides', 'Stop at shoulder height', 'Lower with control'], tips: ['Slight elbow bend', 'Don\'t swing', 'Control tempo'], sets: 3, reps: '12-15' },
  { id: 'ex77', name: 'Leg Curls', category: 'gym', difficulty: 'beginner', equipment: ['Leg Curl Machine'], muscleGroups: ['Hamstrings'], caloriesPerMinute: 5, description: 'Hamstring isolation', instructions: ['Lie face down on machine', 'Curl legs toward glutes', 'Squeeze at top', 'Lower slowly'], tips: ['Don\'t arch back', 'Full range of motion', 'Control weight'], sets: 3, reps: '12-15' },
  { id: 'ex78', name: 'Leg Extensions', category: 'gym', difficulty: 'beginner', equipment: ['Leg Extension Machine'], muscleGroups: ['Quads'], caloriesPerMinute: 5, description: 'Quad isolation exercise', instructions: ['Sit in machine', 'Extend legs fully', 'Pause at top', 'Lower with control'], tips: ['Don\'t lock out violently', 'Control movement', 'Squeeze quads'], sets: 3, reps: '12-15' },
  { id: 'ex79', name: 'Cable Crossovers', category: 'gym', difficulty: 'beginner', equipment: ['Cable Machine'], muscleGroups: ['Chest'], caloriesPerMinute: 5, description: 'Chest isolation', instructions: ['Stand between high cables', 'Bring hands down and together', 'Squeeze chest', 'Return with control'], tips: ['Slight forward lean', 'Fixed elbow angle', 'Feel chest stretch'], sets: 3, reps: '12-15' },
  { id: 'ex80', name: 'Preacher Curls', category: 'gym', difficulty: 'beginner', equipment: ['Preacher Bench', 'Barbell'], muscleGroups: ['Biceps'], caloriesPerMinute: 4, description: 'Bicep isolation', instructions: ['Sit at preacher bench', 'Arms on pad', 'Curl weight up', 'Lower slowly'], tips: ['No swinging', 'Full extension', 'Squeeze at top'], sets: 3, reps: '10-12' },
  
  // HOME - ADVANCED
  { id: 'ex81', name: 'Pistol Squats', category: 'home', difficulty: 'advanced', equipment: [], muscleGroups: ['Quads', 'Glutes', 'Balance'], caloriesPerMinute: 8, description: 'Single leg squat', instructions: ['Stand on one leg', 'Extend other leg forward', 'Squat down on standing leg', 'Stand back up'], tips: ['Use support if needed', 'Keep extended leg straight', 'Go as low as possible'], sets: 3, reps: '5-8 each leg' },
  { id: 'ex82', name: 'Archer Push-ups', category: 'home', difficulty: 'advanced', equipment: [], muscleGroups: ['Chest', 'Triceps', 'Shoulders'], caloriesPerMinute: 8, description: 'One-arm emphasis push-up', instructions: ['Wide push-up position', 'Shift weight to one arm', 'Lower down to that side', 'Push back up', 'Alternate'], tips: ['Keep core tight', 'Control movement', 'One arm does most work'], sets: 3, reps: '6-8 each side' },
  { id: 'ex83', name: 'Dragon Flag', category: 'home', difficulty: 'advanced', equipment: ['Bench'], muscleGroups: ['Core'], caloriesPerMinute: 7, description: 'Advanced core exercise', instructions: ['Lie on bench, grip behind head', 'Lift entire body up', 'Lower slowly keeping straight', 'Just shoulders stay on bench'], tips: ['Very difficult', 'Master progressions first', 'Control descent'], sets: 3, reps: '3-5' },
  { id: 'ex84', name: 'Handstand Push-ups', category: 'home', difficulty: 'advanced', equipment: ['Wall'], muscleGroups: ['Shoulders', 'Triceps'], caloriesPerMinute: 9, description: 'Inverted shoulder press', instructions: ['Kick up to handstand against wall', 'Lower head toward floor', 'Press back up'], tips: ['Use wall for support', 'Full range of motion', 'Build up strength first'], sets: 3, reps: '5-10' },
  { id: 'ex85', name: 'Explosive Push-ups', category: 'home', difficulty: 'advanced', equipment: [], muscleGroups: ['Chest', 'Triceps', 'Power'], caloriesPerMinute: 9, description: 'Plyometric push-up', instructions: ['Regular push-up position', 'Push up explosively', 'Hands leave ground', 'Land softly', 'Repeat'], tips: ['Land under control', 'Maximum power', 'Progress gradually'], sets: 3, reps: '8-12' },

  // YOGA - ADVANCED
  { id: 'ex86', name: 'Headstand (Sirsasana)', category: 'yoga', difficulty: 'advanced', equipment: ['Yoga Mat'], muscleGroups: ['Shoulders', 'Core', 'Balance'], caloriesPerMinute: 5, description: 'Inverted balance pose', instructions: ['Interlace fingers on mat', 'Place crown of head down', 'Walk feet in', 'Lift legs up', 'Balance'], tips: ['Use wall initially', 'Engage core', 'Don\'t put weight on neck'], duration: 60 },
  { id: 'ex87', name: 'Wheel Pose (Urdhva Dhanurasana)', category: 'yoga', difficulty: 'advanced', equipment: ['Yoga Mat'], muscleGroups: ['Back', 'Shoulders', 'Legs'], caloriesPerMinute: 6, description: 'Full backbend', instructions: ['Lie on back, bend knees', 'Hands by ears, fingers toward shoulders', 'Press up into full backbend', 'Straighten arms and legs'], tips: ['Warm up thoroughly', 'Press through hands and feet', 'Open chest'], duration: 30 },
  { id: 'ex88', name: 'Crow Pose (Bakasana)', category: 'yoga', difficulty: 'advanced', equipment: ['Yoga Mat'], muscleGroups: ['Arms', 'Core', 'Balance'], caloriesPerMinute: 5, description: 'Arm balance pose', instructions: ['Squat, hands on mat', 'Knees to upper arms', 'Lean forward', 'Lift feet off ground', 'Balance on hands'], tips: ['Look forward not down', 'Engage core', 'Bend elbows slightly'], duration: 30 },
  { id: 'ex89', name: 'King Pigeon Pose', category: 'yoga', difficulty: 'advanced', equipment: ['Yoga Mat'], muscleGroups: ['Hips', 'Back', 'Shoulders'], caloriesPerMinute: 4, description: 'Deep hip and back opener', instructions: ['Start in pigeon pose', 'Bend back leg', 'Reach back to grab foot', 'Bring to head', 'Arch back'], tips: ['Very deep pose', 'Use strap if needed', 'Breathe into stretch'], duration: 60 },
  { id: 'ex90', name: 'Peacock Pose (Mayurasana)', category: 'yoga', difficulty: 'advanced', equipment: ['Yoga Mat'], muscleGroups: ['Core', 'Arms', 'Wrists'], caloriesPerMinute: 6, description: 'Advanced arm balance', instructions: ['Kneel, hands on floor fingers back', 'Elbows into abdomen', 'Lean forward', 'Lift legs parallel to floor'], tips: ['Very challenging', 'Build wrist strength', 'Elbows together'], duration: 20 },

  // CARDIO - INTERMEDIATE/ADVANCED
  { id: 'ex91', name: 'Broad Jumps', category: 'cardio', difficulty: 'intermediate', equipment: [], muscleGroups: ['Legs', 'Power'], caloriesPerMinute: 10, description: 'Horizontal power jump', instructions: ['Stand ready', 'Swing arms back', 'Jump forward explosively', 'Land softly', 'Reset'], tips: ['Jump for maximum distance', 'Land with bent knees', 'Explosive takeoff'], sets: 3, reps: '8-10' },
  { id: 'ex92', name: 'Rope Climbs', category: 'cardio', difficulty: 'advanced', equipment: ['Rope'], muscleGroups: ['Full Body', 'Grip'], caloriesPerMinute: 11, description: 'Functional pulling exercise', instructions: ['Grip rope high', 'Wrap feet around rope', 'Pull with arms', 'Push with legs', 'Climb to top'], tips: ['Use legs efficiently', 'Strong grip', 'Control descent'], sets: 3, reps: '1-3 climbs' },
  { id: 'ex93', name: 'Sprint Intervals', category: 'cardio', difficulty: 'intermediate', equipment: [], muscleGroups: ['Legs', 'Cardio'], caloriesPerMinute: 14, description: 'High-intensity running', instructions: ['Warm up thoroughly', 'Sprint at 90% max', 'Rest/walk recovery', 'Repeat intervals'], tips: ['Quality over quantity', 'Full recovery between sprints', 'Proper form'], sets: 6, reps: '30 seconds' },
  { id: 'ex94', name: 'Rowing Machine', category: 'cardio', difficulty: 'beginner', equipment: ['Rowing Machine'], muscleGroups: ['Full Body', 'Cardio'], caloriesPerMinute: 11, description: 'Low-impact cardio', instructions: ['Sit in machine', 'Push with legs', 'Pull handle to chest', 'Extend arms, bend knees', 'Repeat'], tips: ['Legs, core, then arms', 'Control the return', 'Maintain posture'], duration: 600 },
  { id: 'ex95', name: 'Stair Climbing', category: 'cardio', difficulty: 'beginner', equipment: ['Stairs'], muscleGroups: ['Legs', 'Cardio'], caloriesPerMinute: 9, description: 'Simple effective cardio', instructions: ['Climb stairs steadily', 'Use handrail if needed', 'Maintain pace', 'Walk down for recovery'], tips: ['Consistent pace', 'Full foot on step', 'Posture upright'], duration: 600 },

  // FUNCTIONAL/CROSSFIT STYLE
  { id: 'ex96', name: 'Kettlebell Swings', category: 'strength', difficulty: 'intermediate', equipment: ['Kettlebell'], muscleGroups: ['Glutes', 'Hamstrings', 'Core', 'Shoulders'], caloriesPerMinute: 10, description: 'Explosive hip hinge exercise', instructions: ['Stand with feet shoulder-width', 'Swing kettlebell back between legs', 'Explosive hip thrust forward', 'Swing to shoulder height', 'Control back swing'], tips: ['Power from hips not arms', 'Flat back', 'Squeeze glutes at top'], sets: 4, reps: '15-20' },
  { id: 'ex97', name: 'Kettlebell Goblet Squat', category: 'strength', difficulty: 'beginner', equipment: ['Kettlebell'], muscleGroups: ['Quads', 'Glutes'], caloriesPerMinute: 7, description: 'Front-loaded squat', instructions: ['Hold kettlebell at chest', 'Squat down between legs', 'Keep elbows inside knees', 'Stand back up'], tips: ['Chest up', 'Deep as possible', 'Elbows push knees out'], sets: 4, reps: '12-15' },
  { id: 'ex98', name: 'Turkish Get-Up', category: 'strength', difficulty: 'advanced', equipment: ['Kettlebell'], muscleGroups: ['Full Body', 'Core', 'Shoulders'], caloriesPerMinute: 8, description: 'Complex full-body movement', instructions: ['Lie down, kettlebell overhead', 'Rise to elbow', 'Rise to hand', 'Sweep leg under', 'Stand up', 'Reverse to lying'], tips: ['Very technical', 'Learn progression', 'Keep eyes on kettlebell'], sets: 3, reps: '3-5 each side' },
  { id: 'ex99', name: 'Wall Balls', category: 'strength', difficulty: 'intermediate', equipment: ['Medicine Ball', 'Wall'], muscleGroups: ['Legs', 'Shoulders', 'Core'], caloriesPerMinute: 10, description: 'Full body power exercise', instructions: ['Hold ball at chest', 'Squat down', 'Explode up', 'Throw ball to target on wall', 'Catch and repeat'], tips: ['Fluid motion', 'Use legs to power throw', 'Catch with soft knees'], sets: 4, reps: '15-20' },
  { id: 'ex100', name: 'Medicine Ball Slams', category: 'strength', difficulty: 'beginner', equipment: ['Medicine Ball'], muscleGroups: ['Core', 'Shoulders', 'Full Body'], caloriesPerMinute: 9, description: 'Power and conditioning', instructions: ['Hold ball overhead', 'Slam down forcefully', 'Catch on bounce', 'Repeat'], tips: ['Use whole body', 'Aggressive slam', 'Non-bouncing ball if available'], sets: 4, reps: '12-15' },

  // MORE GYM EXERCISES
  { id: 'ex101', name: 'Incline Bench Press', category: 'gym', difficulty: 'intermediate', equipment: ['Barbell', 'Incline Bench'], muscleGroups: ['Upper Chest', 'Shoulders', 'Triceps'], caloriesPerMinute: 7, description: 'Upper chest focus press', instructions: ['Lie on incline bench (30-45 degrees)', 'Lower bar to upper chest', 'Press up', 'Lock out'], tips: ['Don\'t bounce', 'Control descent', 'Full range'], sets: 4, reps: '8-12' },
  { id: 'ex102', name: 'Dumbbell Shoulder Press', category: 'gym', difficulty: 'beginner', equipment: ['Dumbbells', 'Bench'], muscleGroups: ['Shoulders', 'Triceps'], caloriesPerMinute: 6, description: 'Shoulder builder', instructions: ['Sit on bench with back support', 'Dumbbells at shoulder height', 'Press overhead', 'Lower with control'], tips: ['Don\'t arch back excessively', 'Full extension', 'Control weight'], sets: 4, reps: '10-12' },
  { id: 'ex103', name: 'Bulgarian Split Squat', category: 'gym', difficulty: 'intermediate', equipment: ['Bench', 'Dumbbells'], muscleGroups: ['Quads', 'Glutes'], caloriesPerMinute: 7, description: 'Single leg squat variation', instructions: ['Back foot on bench', 'Front foot forward', 'Lower down', 'Drive through front heel'], tips: ['Upright torso', 'Front knee tracks over toe', 'Full range'], sets: 3, reps: '10-12 each leg' },
  { id: 'ex104', name: 'Cable Rows', category: 'gym', difficulty: 'beginner', equipment: ['Cable Machine'], muscleGroups: ['Back', 'Biceps'], caloriesPerMinute: 6, description: 'Mid-back exercise', instructions: ['Sit at cable row machine', 'Pull handle to torso', 'Squeeze shoulder blades', 'Return with control'], tips: ['Keep back straight', 'Don\'t use momentum', 'Pull to lower chest'], sets: 4, reps: '10-12' },
  { id: 'ex105', name: 'Hammer Curls', category: 'gym', difficulty: 'beginner', equipment: ['Dumbbells'], muscleGroups: ['Biceps', 'Forearms'], caloriesPerMinute: 4, description: 'Bicep and forearm exercise', instructions: ['Hold dumbbells with neutral grip', 'Curl up', 'Keep elbows stationary', 'Lower slowly'], tips: ['Thumbs up position', 'No swinging', 'Squeeze at top'], sets: 3, reps: '12-15' },

  // MORE HOME EXERCISES
  { id: 'ex106', name: 'Decline Push-ups', category: 'home', difficulty: 'intermediate', equipment: ['Chair/Box'], muscleGroups: ['Upper Chest', 'Shoulders', 'Triceps'], caloriesPerMinute: 7, description: 'Elevated feet push-up', instructions: ['Feet on elevated surface', 'Hands on ground', 'Lower chest to ground', 'Push back up'], tips: ['Keep body straight', 'More shoulder engagement', 'Control movement'], sets: 3, reps: '12-15' },
  { id: 'ex107', name: 'Calf Raises', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Calves'], caloriesPerMinute: 4, description: 'Calf strengthening', instructions: ['Stand on edge of step', 'Rise up on toes', 'Lower heels below step level', 'Repeat'], tips: ['Full range of motion', 'Hold at top', 'Control descent'], sets: 3, reps: '15-20' },
  { id: 'ex108', name: 'Bear Crawls', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Full Body', 'Core'], caloriesPerMinute: 8, description: 'Quadrupedal movement', instructions: ['On hands and feet', 'Crawl forward', 'Keep hips low', 'Coordinated movement'], tips: ['Core engaged', 'Opposite hand and foot', 'Keep back flat'], sets: 3, reps: '30 seconds' },
  { id: 'ex109', name: 'Inchworms', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Core', 'Shoulders', 'Hamstrings'], caloriesPerMinute: 6, description: 'Dynamic stretch and strength', instructions: ['Stand, bend to touch floor', 'Walk hands out to plank', 'Walk hands back to feet', 'Stand up'], tips: ['Keep legs straight', 'Full plank position', 'Controlled movement'], sets: 3, reps: '8-10' },
  { id: 'ex110', name: 'Side Plank', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Obliques', 'Core', 'Shoulders'], caloriesPerMinute: 4, description: 'Lateral core stability', instructions: ['Lie on side', 'Prop up on forearm', 'Lift hips off ground', 'Hold straight line'], tips: ['Stack feet', 'Hips forward', 'Don\'t sag'], duration: 45 },

  // SPORTS & AGILITY
  { id: 'ex111', name: 'Ladder Drills', category: 'sports', difficulty: 'intermediate', equipment: ['Agility Ladder'], muscleGroups: ['Legs', 'Coordination'], caloriesPerMinute: 9, description: 'Footwork and agility training', instructions: ['Set up agility ladder', 'Perform various patterns', 'High knees through ladder', 'Quick feet'], tips: ['Stay on toes', 'Quick feet', 'Look ahead'], sets: 5, reps: '1 length' },
  { id: 'ex112', name: 'Cone Drills', category: 'sports', difficulty: 'beginner', equipment: ['Cones'], muscleGroups: ['Legs', 'Agility'], caloriesPerMinute: 8, description: 'Change of direction drills', instructions: ['Set up cone pattern', 'Sprint between cones', 'Sharp cuts', 'Low center of gravity'], tips: ['Plant and cut', 'Explosive changes', 'Stay low'], sets: 5, reps: '30 seconds' },
  { id: 'ex113', name: 'Plyometric Jumps', category: 'sports', difficulty: 'intermediate', equipment: [], muscleGroups: ['Legs', 'Power'], caloriesPerMinute: 11, description: 'Explosive jump training', instructions: ['Jump from ground to box', 'Immediately jump back down', 'Minimal ground contact time', 'Repeat'], tips: ['Explosive effort', 'Soft landing', 'Quick turnaround'], sets: 4, reps: '6-8' },
  { id: 'ex114', name: 'Yoga Ball Exercises', category: 'flexibility', difficulty: 'beginner', equipment: ['Yoga Ball'], muscleGroups: ['Core', 'Balance'], caloriesPerMinute: 5, description: 'Stability ball training', instructions: ['Various exercises on ball', 'Balance challenges', 'Core engagement', 'Controlled movements'], tips: ['Maintain balance', 'Engage core constantly', 'Progress gradually'], sets: 3, reps: '12-15' },
  { id: 'ex115', name: 'Band Pull-Aparts', category: 'flexibility', difficulty: 'beginner', equipment: ['Resistance Band'], muscleGroups: ['Upper Back', 'Shoulders'], caloriesPerMinute: 3, description: 'Shoulder health exercise', instructions: ['Hold band at shoulder height', 'Pull apart to sides', 'Squeeze shoulder blades', 'Return slowly'], tips: ['Keep arms straight', 'Control movement', 'Feel upper back work'], sets: 3, reps: '15-20' },

  // FLEXIBILITY & MOBILITY
  { id: 'ex116', name: 'Hip Flexor Stretch', category: 'flexibility', difficulty: 'beginner', equipment: [], muscleGroups: ['Hip Flexors'], caloriesPerMinute: 2, description: 'Hip opener stretch', instructions: ['Lunge position', 'Back knee on ground', 'Push hips forward', 'Feel stretch in front of hip'], tips: ['Keep torso upright', 'Don\'t overarch back', 'Hold steady'], duration: 60 },
  { id: 'ex117', name: 'Hamstring Stretch', category: 'flexibility', difficulty: 'beginner', equipment: [], muscleGroups: ['Hamstrings'], caloriesPerMinute: 2, description: 'Hamstring flexibility', instructions: ['Sit with one leg extended', 'Reach toward toe', 'Keep back straight', 'Hold stretch'], tips: ['Don\'t bounce', 'Breathe into stretch', 'Gradual progression'], duration: 60 },
  { id: 'ex118', name: 'Quad Stretch', category: 'flexibility', difficulty: 'beginner', equipment: [], muscleGroups: ['Quads'], caloriesPerMinute: 2, description: 'Quadriceps stretch', instructions: ['Stand on one leg', 'Pull other foot to glutes', 'Keep knees together', 'Hold'], tips: ['Use wall for balance', 'Don\'t arch back', 'Feel front thigh stretch'], duration: 60 },
  { id: 'ex119', name: 'Chest Stretch', category: 'flexibility', difficulty: 'beginner', equipment: ['Doorway'], muscleGroups: ['Chest', 'Shoulders'], caloriesPerMinute: 2, description: 'Chest and shoulder opener', instructions: ['Stand in doorway', 'Place forearm on frame', 'Step forward', 'Feel chest stretch'], tips: ['Various arm heights', 'Don\'t force', 'Breathe deeply'], duration: 60 },
  { id: 'ex120', name: 'Shoulder Dislocations', category: 'flexibility', difficulty: 'beginner', equipment: ['PVC Pipe/Band'], muscleGroups: ['Shoulders'], caloriesPerMinute: 3, description: 'Shoulder mobility exercise', instructions: ['Hold pipe wide grip', 'Rotate over and behind', 'Keep arms straight', 'Return to front'], tips: ['Start with wide grip', 'Gradually narrow grip', 'Controlled movement'], sets: 3, reps: '10-15' },

  // CORE FOCUSED
  { id: 'ex121', name: 'Dead Bug', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Core'], caloriesPerMinute: 4, description: 'Core stability exercise', instructions: ['Lie on back', 'Arms and legs up', 'Lower opposite arm and leg', 'Return and alternate'], tips: ['Keep back flat', 'Slow and controlled', 'Breathe steadily'], sets: 3, reps: '10-12 each side' },
  { id: 'ex122', name: 'Pallof Press', category: 'gym', difficulty: 'beginner', equipment: ['Cable Machine'], muscleGroups: ['Core', 'Anti-rotation'], caloriesPerMinute: 5, description: 'Anti-rotation core exercise', instructions: ['Stand sideways to cable', 'Hold handle at chest', 'Press straight out', 'Resist rotation', 'Return'], tips: ['Maintain square stance', 'Core engaged', 'Don\'t let cable pull you'], sets: 3, reps: '10-12 each side' },
  { id: 'ex123', name: 'Ab Wheel Rollout', category: 'home', difficulty: 'advanced', equipment: ['Ab Wheel'], muscleGroups: ['Core', 'Shoulders'], caloriesPerMinute: 7, description: 'Advanced core exercise', instructions: ['Kneel with ab wheel', 'Roll forward', 'Extend as far as possible', 'Roll back to start'], tips: ['Keep core braced', 'Don\'t sag hips', 'Start from knees'], sets: 3, reps: '8-12' },
  { id: 'ex124', name: 'Hanging Knee Raises', category: 'gym', difficulty: 'intermediate', equipment: ['Pull-up Bar'], muscleGroups: ['Lower Abs', 'Hip Flexors'], caloriesPerMinute: 6, description: 'Lower ab exercise', instructions: ['Hang from bar', 'Raise knees to chest', 'Lower with control', 'Avoid swinging'], tips: ['Controlled movement', 'Engage abs not hip flexors', 'Progress to straight legs'], sets: 3, reps: '10-15' },
  { id: 'ex125', name: 'L-Sit Hold', category: 'home', difficulty: 'advanced', equipment: ['Parallettes/Floor'], muscleGroups: ['Core', 'Hip Flexors', 'Shoulders'], caloriesPerMinute: 6, description: 'Static core strength', instructions: ['Support on hands', 'Lift legs straight out', 'Hold L-position', 'Maintain posture'], tips: ['Start with bent knees', 'Push shoulders down', 'Engage entire core'], duration: 30 },

  // OLYMPIC/POWER LIFTS
  { id: 'ex126', name: 'Power Clean', category: 'gym', difficulty: 'advanced', equipment: ['Barbell'], muscleGroups: ['Full Body', 'Power'], caloriesPerMinute: 11, description: 'Olympic lift variation', instructions: ['Deadlift starting position', 'Explosive triple extension', 'Pull bar high', 'Drop under and catch', 'Stand up'], tips: ['Very technical', 'Learn proper form', 'Start light'], sets: 5, reps: '3-5' },
  { id: 'ex127', name: 'Snatch', category: 'gym', difficulty: 'advanced', equipment: ['Barbell'], muscleGroups: ['Full Body', 'Power'], caloriesPerMinute: 12, description: 'Olympic weightlifting', instructions: ['Wide grip on bar', 'Explosive pull', 'Drop under bar', 'Catch overhead in squat', 'Stand up'], tips: ['Extremely technical', 'Coaching recommended', 'Mobility required'], sets: 5, reps: '2-3' },
  { id: 'ex128', name: 'Sumo Deadlift', category: 'gym', difficulty: 'intermediate', equipment: ['Barbell'], muscleGroups: ['Legs', 'Back', 'Glutes'], caloriesPerMinute: 10, description: 'Wide stance deadlift', instructions: ['Wide stance, toes out', 'Grip bar between legs', 'Keep torso more upright', 'Drive through heels'], tips: ['Open hips', 'Vertical back angle', 'Push floor away'], sets: 4, reps: '5-8' },
  { id: 'ex129', name: 'Thruster', category: 'strength', difficulty: 'intermediate', equipment: ['Barbell'], muscleGroups: ['Full Body'], caloriesPerMinute: 11, description: 'Squat to press combo', instructions: ['Front squat position', 'Squat down', 'Drive up explosively', 'Press bar overhead', 'Lower and repeat'], tips: ['One fluid motion', 'Use leg drive', 'Full lockout'], sets: 4, reps: '8-12' },
  { id: 'ex130', name: 'Clean and Jerk', category: 'gym', difficulty: 'advanced', equipment: ['Barbell'], muscleGroups: ['Full Body', 'Power'], caloriesPerMinute: 12, description: 'Olympic lift', instructions: ['Clean bar to shoulders', 'Dip and drive', 'Split or squat jerk', 'Lock out overhead', 'Recover'], tips: ['Two distinct movements', 'Technical complexity', 'Coaching recommended'], sets: 5, reps: '2-3' },

  // MORE HIIT & CONDITIONING
  { id: 'ex131', name: 'Assault Bike', category: 'cardio', difficulty: 'intermediate', equipment: ['Assault Bike'], muscleGroups: ['Full Body', 'Cardio'], caloriesPerMinute: 13, description: 'High-intensity bike intervals', instructions: ['Sit on bike', 'Push and pull handles', 'Pedal hard', 'Maintain intensity'], tips: ['All-out effort for intervals', 'Full body engagement', 'Pace yourself'], sets: 5, reps: '30 seconds' },
  { id: 'ex132', name: 'Sled Push', category: 'strength', difficulty: 'intermediate', equipment: ['Sled'], muscleGroups: ['Legs', 'Full Body'], caloriesPerMinute: 11, description: 'Power and conditioning', instructions: ['Hands on sled', 'Drive through legs', 'Push forward', 'Maintain low position'], tips: ['Stay low', 'Drive with legs', 'Continuous pressure'], sets: 5, reps: '30 seconds' },
  { id: 'ex133', name: 'Sled Pull', category: 'strength', difficulty: 'intermediate', equipment: ['Sled', 'Rope'], muscleGroups: ['Back', 'Legs'], caloriesPerMinute: 10, description: 'Pulling conditioning', instructions: ['Attach rope to sled', 'Pull hand over hand', 'Walk backward', 'Maintain tension'], tips: ['Strong pulls', 'Engage back', 'Steady pace'], sets: 5, reps: '30 seconds' },
  { id: 'ex134', name: 'Prowler Push', category: 'strength', difficulty: 'intermediate', equipment: ['Prowler'], muscleGroups: ['Legs', 'Conditioning'], caloriesPerMinute: 12, description: 'Leg power and conditioning', instructions: ['Grip prowler handles', 'Drive forward with legs', 'Maintain forward lean', 'Push for distance'], tips: ['Explosive drives', 'Keep pushing', 'Don\'t stand up'], sets: 5, reps: '30 seconds' },
  { id: 'ex135', name: 'Tire Flips', category: 'strength', difficulty: 'advanced', equipment: ['Large Tire'], muscleGroups: ['Full Body', 'Power'], caloriesPerMinute: 13, description: 'Functional strength exercise', instructions: ['Squat and grip tire', 'Drive up with legs', 'Push tire over', 'Reset and repeat'], tips: ['Use legs not back', 'Explosive movement', 'Proper form critical'], sets: 3, reps: '5-10' },

  // BODYWEIGHT CHALLENGES
  { id: 'ex136', name: 'Muscle-Ups', category: 'home', difficulty: 'advanced', equipment: ['Pull-up Bar'], muscleGroups: ['Back', 'Chest', 'Triceps'], caloriesPerMinute: 10, description: 'Advanced pull-up to dip', instructions: ['Explosive pull-up', 'Transition over bar', 'Press to full lockout', 'Lower down'], tips: ['Build strength first', 'Explosive pull', 'Quick transition'], sets: 3, reps: '3-5' },
  { id: 'ex137', name: 'One-Arm Push-up', category: 'home', difficulty: 'advanced', equipment: [], muscleGroups: ['Chest', 'Triceps', 'Core'], caloriesPerMinute: 8, description: 'Advanced push-up variation', instructions: ['Wide stance', 'One hand behind back', 'Lower down', 'Push up', 'Maintain balance'], tips: ['Start elevated', 'Wide feet', 'Control movement'], sets: 3, reps: '3-5 each arm' },
  { id: 'ex138', name: 'Front Lever', category: 'home', difficulty: 'advanced', equipment: ['Pull-up Bar'], muscleGroups: ['Core', 'Back', 'Shoulders'], caloriesPerMinute: 7, description: 'Advanced static hold', instructions: ['Hang from bar', 'Raise body parallel to ground', 'Hold horizontal position', 'Entire body straight'], tips: ['Very advanced', 'Build with progressions', 'Massive core strength needed'], duration: 20 },
  { id: 'ex139', name: 'Human Flag', category: 'home', difficulty: 'advanced', equipment: ['Vertical Pole'], muscleGroups: ['Core', 'Shoulders', 'Obliques'], caloriesPerMinute: 8, description: 'Extreme strength hold', instructions: ['Grip pole vertically', 'Lift body horizontal', 'Hold sideways position', 'Top arm pushes, bottom pulls'], tips: ['Extremely difficult', 'Years of training', 'Build shoulder and core strength'], duration: 10 },
  { id: 'ex140', name: 'Planche', category: 'home', difficulty: 'advanced', equipment: [], muscleGroups: ['Shoulders', 'Core', 'Chest'], caloriesPerMinute: 7, description: 'Advanced balance hold', instructions: ['Hands on ground', 'Lean forward', 'Lift feet off ground', 'Hold body parallel to ground'], tips: ['Elite-level skill', 'Requires years', 'Many progressions needed'], duration: 10 },

  // TRADITIONAL INDIAN EXERCISES
  { id: 'ex141', name: 'Dand (Hindu Push-ups)', category: 'home', difficulty: 'intermediate', equipment: [], muscleGroups: ['Chest', 'Shoulders', 'Core'], caloriesPerMinute: 8, description: 'Traditional Indian exercise', instructions: ['Start in downward dog', 'Swoop down and forward', 'Arch into upward dog', 'Push back to start'], tips: ['Fluid movement', 'Build endurance', 'Traditional wrestler exercise'], sets: 3, reps: '15-20' },
  { id: 'ex142', name: 'Baithak (Hindu Squats)', category: 'home', difficulty: 'beginner', equipment: [], muscleGroups: ['Legs', 'Cardio'], caloriesPerMinute: 7, description: 'Traditional Indian squat', instructions: ['Stand with feet together', 'Squat down on toes', 'Swing arms', 'Stand up', 'Continuous rhythm'], tips: ['Fast pace', 'High reps', 'Wrestler conditioning'], sets: 3, reps: '25-50' },
  { id: 'ex143', name: 'Gada (Mace) Swinging', category: 'strength', difficulty: 'intermediate', equipment: ['Mace'], muscleGroups: ['Shoulders', 'Core', 'Grip'], caloriesPerMinute: 8, description: 'Traditional strength tool', instructions: ['Hold mace handle', 'Swing in controlled arcs', 'Various patterns', 'Build shoulder strength'], tips: ['Start with light mace', 'Control the weight', 'Traditional Indian training'], sets: 3, reps: '10-15 each direction' },
  { id: 'ex144', name: 'Jori (Club) Swinging', category: 'strength', difficulty: 'beginner', equipment: ['Clubs'], muscleGroups: ['Shoulders', 'Arms', 'Wrists'], caloriesPerMinute: 6, description: 'Traditional club exercise', instructions: ['Hold clubs in each hand', 'Swing in circles', 'Various patterns', 'Coordination training'], tips: ['Start light', 'Build gradually', 'Traditional conditioning'], sets: 3, reps: '20-30 circles' },
  { id: 'ex145', name: 'Mallakhamb Training', category: 'sports', difficulty: 'advanced', equipment: ['Pole'], muscleGroups: ['Full Body', 'Core'], caloriesPerMinute: 9, description: 'Traditional Indian pole gymnastics', instructions: ['Climb vertical pole', 'Perform various poses', 'Static and dynamic holds', 'Combination movements'], tips: ['Very traditional', 'Builds incredible strength', 'Indian martial training'], duration: 300 },

  // BREATHING & MEDITATION MOVEMENT
  { id: 'ex146', name: 'Pranayama Exercises', category: 'yoga', difficulty: 'beginner', equipment: ['Yoga Mat'], muscleGroups: ['Respiratory'], caloriesPerMinute: 2, description: 'Yogic breathing exercises', instructions: ['Sit comfortably', 'Practice various breathing techniques', 'Anulom Vilom, Kapalbhati', 'Focus on breath'], tips: ['Practice on empty stomach', 'Regular practice', 'Improves lung capacity'], duration: 300 },
  { id: 'ex147', name: 'Kapalbhati', category: 'yoga', difficulty: 'beginner', equipment: ['Yoga Mat'], muscleGroups: ['Core', 'Respiratory'], caloriesPerMinute: 3, description: 'Breathing cleansing technique', instructions: ['Sit in comfortable position', 'Forceful exhales through nose', 'Passive inhales', 'Engage abdomen on exhale'], tips: ['Start slow', 'Build speed gradually', 'Cleansing breath'], duration: 180 },
  { id: 'ex148', name: 'Walking Meditation', category: 'yoga', difficulty: 'beginner', equipment: [], muscleGroups: ['Legs', 'Mind'], caloriesPerMinute: 3, description: 'Mindful walking practice', instructions: ['Walk slowly and deliberately', 'Focus on each step', 'Breath awareness', 'Present moment focus'], tips: ['Very slow pace', 'Complete awareness', 'Mind-body connection'], duration: 600 },
  { id: 'ex149', name: 'Tai Chi', category: 'martial-arts', difficulty: 'beginner', equipment: [], muscleGroups: ['Full Body', 'Balance'], caloriesPerMinute: 4, description: 'Moving meditation', instructions: ['Slow, flowing movements', 'Weight shifts', 'Balance and control', 'Breath coordination'], tips: ['Very slow and controlled', 'Focus on form', 'Meditative practice'], duration: 600 },
  { id: 'ex150', name: 'Qi Gong', category: 'flexibility', difficulty: 'beginner', equipment: [], muscleGroups: ['Full Body', 'Energy'], caloriesPerMinute: 3, description: 'Chinese energy practice', instructions: ['Gentle flowing movements', 'Breath work', 'Energy cultivation', 'Mind-body integration'], tips: ['Gentle practice', 'Focus on energy', 'Regular practice beneficial'], duration: 600 },

  // MOBILITY & WARMUP
  { id: 'ex151', name: 'Arm Circles', category: 'flexibility', difficulty: 'beginner', equipment: [], muscleGroups: ['Shoulders'], caloriesPerMinute: 3, description: 'Shoulder warm-up', instructions: ['Extend arms to sides', 'Make circles', 'Forward and backward', 'Gradually increase size'], tips: ['Start small circles', 'Progress to large', 'Both directions'], sets: 2, reps: '20 each direction' },
  { id: 'ex152', name: 'Leg Swings', category: 'flexibility', difficulty: 'beginner', equipment: [], muscleGroups: ['Hips', 'Legs'], caloriesPerMinute: 4, description: 'Dynamic hip mobility', instructions: ['Hold support', 'Swing leg forward and back', 'Side to side', 'Controlled swings'], tips: ['Gradually increase range', 'Stay balanced', 'Don\'t force'], sets: 2, reps: '15 each leg' },
  { id: 'ex153', name: 'World\'s Greatest Stretch', category: 'flexibility', difficulty: 'beginner', equipment: [], muscleGroups: ['Full Body'], caloriesPerMinute: 4, description: 'Full body dynamic stretch', instructions: ['Lunge forward', 'Hand to ground inside foot', 'Rotate up to sky', 'Return and switch'], tips: ['Hold each position', 'Full range of motion', 'Great warm-up'], sets: 2, reps: '5 each side' },
  { id: 'ex154', name: 'Spiderman Stretch', category: 'flexibility', difficulty: 'beginner', equipment: [], muscleGroups: ['Hips', 'Groin'], caloriesPerMinute: 4, description: 'Hip mobility stretch', instructions: ['Push-up position', 'Bring foot outside hand', 'Drop hips down', 'Hold and switch'], tips: ['Feel hip stretch', 'Keep back leg straight', 'Dynamic or static'], sets: 2, reps: '8-10 each side' },
  { id: 'ex155', name: 'Scorpion Stretch', category: 'flexibility', difficulty: 'intermediate', equipment: [], muscleGroups: ['Back', 'Hips', 'Shoulders'], caloriesPerMinute: 4, description: 'Rotational mobility', instructions: ['Lie face down, arms out', 'Lift leg up and across body', 'Rotate spine', 'Return and switch'], tips: ['Control movement', 'Full rotation', 'Great for mobility'], sets: 2, reps: '8-10 each side' },

  // GRIP & FOREARM
  { id: 'ex156', name: 'Farmer\'s Hold', category: 'strength', difficulty: 'beginner', equipment: ['Dumbbells'], muscleGroups: ['Grip', 'Forearms'], caloriesPerMinute: 3, description: 'Static grip hold', instructions: ['Hold heavy dumbbells', 'Stand still', 'Hold for time', 'Don\'t shrug shoulders'], tips: ['Maximum weight', 'Timed hold', 'Builds grip strength'], duration: 60 },
  { id: 'ex157', name: 'Wrist Curls', category: 'gym', difficulty: 'beginner', equipment: ['Dumbbells'], muscleGroups: ['Forearms'], caloriesPerMinute: 3, description: 'Forearm isolation', instructions: ['Forearms on bench', 'Wrists hanging off', 'Curl weight up', 'Lower slowly'], tips: ['Full range of motion', 'Both sides', 'Build forearm strength'], sets: 3, reps: '15-20' },
  { id: 'ex158', name: 'Dead Hangs', category: 'home', difficulty: 'beginner', equipment: ['Pull-up Bar'], muscleGroups: ['Grip', 'Forearms'], caloriesPerMinute: 3, description: 'Grip endurance', instructions: ['Hang from bar', 'Fully extended', 'Hold for time', 'Relax shoulders'], tips: ['Active vs passive hang', 'Build time gradually', 'Improves pull-ups'], duration: 60 },
  { id: 'ex159', name: 'Plate Pinches', category: 'gym', difficulty: 'beginner', equipment: ['Weight Plates'], muscleGroups: ['Grip', 'Fingers'], caloriesPerMinute: 3, description: 'Pinch grip strength', instructions: ['Pinch weight plates together', 'Hold at side', 'Maintain grip', 'Hold for time'], tips: ['Thumb opposite fingers', 'Heavy plates', 'Timed holds'], duration: 45 },
  { id: 'ex160', name: 'Towel Pull-ups', category: 'home', difficulty: 'advanced', equipment: ['Pull-up Bar', 'Towel'], muscleGroups: ['Back', 'Grip'], caloriesPerMinute: 9, description: 'Extreme grip pull-ups', instructions: ['Drape towel over bar', 'Grip towel ends', 'Pull up', 'Very challenging grip'], tips: ['Extremely hard', 'Builds crushing grip', 'Progress gradually'], sets: 3, reps: '5-8' },

  // COOL DOWN & RECOVERY
  { id: 'ex161', name: 'Foam Rolling', category: 'flexibility', difficulty: 'beginner', equipment: ['Foam Roller'], muscleGroups: ['Full Body'], caloriesPerMinute: 2, description: 'Self-myofascial release', instructions: ['Roll tight muscles', 'Slow rolling motion', 'Pause on tender spots', 'Breathe through it'], tips: ['Not on joints', 'Gradual pressure', 'Daily practice helpful'], duration: 300 },
  { id: 'ex162', name: 'Lacrosse Ball Massage', category: 'flexibility', difficulty: 'beginner', equipment: ['Lacrosse Ball'], muscleGroups: ['Full Body'], caloriesPerMinute: 2, description: 'Targeted muscle release', instructions: ['Place ball on tight area', 'Apply body weight', 'Roll slowly', 'Focus on knots'], tips: ['More targeted than foam roller', 'Breathe through pressure', 'Regular practice'], duration: 300 },
  { id: 'ex163', name: 'Static Stretching Routine', category: 'flexibility', difficulty: 'beginner', equipment: [], muscleGroups: ['Full Body'], caloriesPerMinute: 2, description: 'Post-workout stretches', instructions: ['Hold each stretch 30-60 seconds', 'All major muscle groups', 'Breathe deeply', 'Relax into stretches'], tips: ['After workout only', 'Don\'t bounce', 'Gradual progression'], duration: 600 },
  { id: 'ex164', name: 'Corpse Pose (Savasana)', category: 'yoga', difficulty: 'beginner', equipment: ['Yoga Mat'], muscleGroups: ['Full Body Recovery'], caloriesPerMinute: 1, description: 'Final relaxation pose', instructions: ['Lie flat on back', 'Arms at sides', 'Palms up', 'Complete relaxation', 'Focus on breath'], tips: ['Don\'t skip this', 'Complete relaxation', 'Integrate practice'], duration: 300 },
  { id: 'ex165', name: 'Deep Breathing Exercise', category: 'yoga', difficulty: 'beginner', equipment: [], muscleGroups: ['Respiratory'], caloriesPerMinute: 2, description: 'Calming breath work', instructions: ['Sit or lie comfortably', 'Deep inhales through nose', 'Slow exhales', 'Focus on breath'], tips: ['4-7-8 breathing pattern', 'Calms nervous system', 'Great before bed'], duration: 300 },

  // ADDITIONAL STRENGTH VARIATIONS
  { id: 'ex166', name: 'Zercher Squat', category: 'gym', difficulty: 'advanced', equipment: ['Barbell'], muscleGroups: ['Quads', 'Core', 'Upper Back'], caloriesPerMinute: 9, description: 'Front-loaded squat variation', instructions: ['Hold bar in elbow crease', 'Squat down', 'Keep torso upright', 'Drive up'], tips: ['Use pad for comfort', 'Very challenging', 'Great core work'], sets: 4, reps: '6-8' },
  { id: 'ex167', name: 'Anderson Squat', category: 'gym', difficulty: 'intermediate', equipment: ['Barbell', 'Squat Rack'], muscleGroups: ['Quads', 'Glutes'], caloriesPerMinute: 8, description: 'Bottom-up squat', instructions: ['Start with bar on pins at bottom', 'Squat under bar', 'Drive up to standing', 'Lower back to pins'], tips: ['Builds power from bottom', 'No eccentric', 'Great for strength'], sets: 4, reps: '5-8' },
  { id: 'ex168', name: 'Pause Squats', category: 'gym', difficulty: 'intermediate', equipment: ['Barbell'], muscleGroups: ['Quads', 'Glutes'], caloriesPerMinute: 8, description: 'Squat with pause at bottom', instructions: ['Squat down normally', 'Pause at bottom for 2-3 seconds', 'Drive up', 'No bouncing'], tips: ['Builds strength at weak point', 'Use lighter weight', 'True test of strength'], sets: 4, reps: '5-8' },
  { id: 'ex169', name: 'Tempo Squats', category: 'gym', difficulty: 'intermediate', equipment: ['Barbell'], muscleGroups: ['Quads', 'Glutes'], caloriesPerMinute: 7, description: 'Controlled tempo squat', instructions: ['3-second descent', '1-second pause', 'Explosive up', '1-second at top'], tips: ['Builds control', 'Time under tension', 'Use lighter weight'], sets: 4, reps: '6-10' },
  { id: 'ex170', name: 'Pendlay Rows', category: 'gym', difficulty: 'intermediate', equipment: ['Barbell'], muscleGroups: ['Back', 'Biceps'], caloriesPerMinute: 7, description: 'Explosive barbell row', instructions: ['Bend over 90 degrees', 'Bar on floor each rep', 'Explosive pull to chest', 'Lower to floor'], tips: ['Reset each rep', 'Explosive', 'Horizontal back'], sets: 4, reps: '6-8' },

  // BODYWEIGHT SKILL WORK
  { id: 'ex171', name: 'Frog Stand', category: 'home', difficulty: 'intermediate', equipment: [], muscleGroups: ['Core', 'Shoulders', 'Balance'], caloriesPerMinute: 5, description: 'Beginner arm balance', instructions: ['Squat down', 'Hands on floor', 'Knees on elbows', 'Lean forward until feet lift'], tips: ['Good first arm balance', 'Progress to crow pose', 'Build shoulder strength'], duration: 30 },
  { id: 'ex172', name: 'Tuck Planche', category: 'home', difficulty: 'advanced', equipment: [], muscleGroups: ['Shoulders', 'Core'], caloriesPerMinute: 6, description: 'Planche progression', instructions: ['Hands on ground', 'Lean forward', 'Tuck knees to chest', 'Hold parallel to ground'], tips: ['Planche progression', 'Build gradually', 'Strong shoulders needed'], duration: 20 },
  { id: 'ex173', name: 'Skin the Cat', category: 'home', difficulty: 'intermediate', equipment: ['Pull-up Bar'], muscleGroups: ['Shoulders', 'Core'], caloriesPerMinute: 5, description: 'Shoulder mobility and strength', instructions: ['Hang from bar', 'Lift legs and rotate backward', 'Continue until inverted', 'Reverse motion'], tips: ['Great shoulder mobility', 'Build strength', 'Progress slowly'], sets: 3, reps: '5-8' },
  { id: 'ex174', name: 'Tucked Front Lever', category: 'home', difficulty: 'advanced', equipment: ['Pull-up Bar'], muscleGroups: ['Core', 'Back'], caloriesPerMinute: 6, description: 'Front lever progression', instructions: ['Hang from bar', 'Pull into tuck position', 'Hold horizontal', 'Body parallel to ground'], tips: ['Front lever progression', 'Very demanding', 'Build with holds'], duration: 20 },
  { id: 'ex175', name: 'Handstand Hold', category: 'home', difficulty: 'advanced', equipment: ['Wall'], muscleGroups: ['Shoulders', 'Core', 'Balance'], caloriesPerMinute: 5, description: 'Inverted balance', instructions: ['Kick up to handstand', 'Use wall for support', 'Hold straight line', 'Engage entire body'], tips: ['Build time gradually', 'Hollow body position', 'Progress to free-standing'], duration: 60 },

  // ADDITIONAL CARDIO
  { id: 'ex176', name: 'Elliptical Machine', category: 'cardio', difficulty: 'beginner', equipment: ['Elliptical'], muscleGroups: ['Full Body', 'Cardio'], caloriesPerMinute: 8, description: 'Low-impact cardio', instructions: ['Step on pedals', 'Push and pull handles', 'Maintain steady rhythm', 'Adjust resistance'], tips: ['Low impact on joints', 'Full body cardio', 'Adjust intensity'], duration: 600 },
  { id: 'ex177', name: 'Swimming', category: 'cardio', difficulty: 'intermediate', equipment: ['Pool'], muscleGroups: ['Full Body'], caloriesPerMinute: 10, description: 'Full body cardio workout', instructions: ['Choose stroke', 'Maintain form', 'Steady pace or intervals', 'Breathe rhythmically'], tips: ['Excellent full body workout', 'Low impact', 'Learn proper technique'], duration: 600 },
  { id: 'ex178', name: 'Cycling', category: 'cardio', difficulty: 'beginner', equipment: ['Bicycle'], muscleGroups: ['Legs', 'Cardio'], caloriesPerMinute: 9, description: 'Outdoor or indoor cycling', instructions: ['Adjust bike fit', 'Maintain cadence', 'Vary terrain/resistance', 'Good posture'], tips: ['Great for endurance', 'Low impact', 'Outdoor or stationary'], duration: 1200 },
  { id: 'ex179', name: 'Running', category: 'cardio', difficulty: 'beginner', equipment: ['Running Shoes'], muscleGroups: ['Legs', 'Cardio'], caloriesPerMinute: 11, description: 'Classic cardio exercise', instructions: ['Good running form', 'Land midfoot', 'Relaxed shoulders', 'Controlled breathing'], tips: ['Start with walk/run intervals', 'Good shoes important', 'Build gradually'], duration: 1200 },
  { id: 'ex180', name: 'Brisk Walking', category: 'cardio', difficulty: 'beginner', equipment: [], muscleGroups: ['Legs', 'Cardio'], caloriesPerMinute: 5, description: 'Low-intensity steady state cardio', instructions: ['Walk at fast pace', 'Pump arms', 'Good posture', 'Maintain pace'], tips: ['Great for beginners', 'Low impact', 'Daily habit'], duration: 1800 },

  // COMPOUND MOVEMENTS
  { id: 'ex181', name: 'Dumbbell Clean and Press', category: 'gym', difficulty: 'intermediate', equipment: ['Dumbbells'], muscleGroups: ['Full Body'], caloriesPerMinute: 9, description: 'Full body power exercise', instructions: ['Clean dumbbells to shoulders', 'Press overhead', 'Lower to shoulders', 'Lower to start'], tips: ['Explosive movement', 'Full body integration', 'Good for conditioning'], sets: 4, reps: '8-12' },
  { id: 'ex182', name: 'Landmine Press', category: 'gym', difficulty: 'beginner', equipment: ['Barbell', 'Landmine'], muscleGroups: ['Shoulders', 'Core'], caloriesPerMinute: 6, description: 'Angled overhead press', instructions: ['Hold end of landmine bar', 'Press up at angle', 'Control descent', 'Repeat'], tips: ['Shoulder-friendly', 'Core engagement', 'Can do single arm'], sets: 3, reps: '10-12' },
  { id: 'ex183', name: 'Landmine Rotation', category: 'gym', difficulty: 'beginner', equipment: ['Barbell', 'Landmine'], muscleGroups: ['Core', 'Obliques'], caloriesPerMinute: 6, description: 'Rotational core exercise', instructions: ['Hold landmine bar', 'Rotate side to side', 'Control movement', 'Engage core'], tips: ['Great for rotation', 'Athletic movement', 'Both sides'], sets: 3, reps: '12-15 each side' },
  { id: 'ex184', name: 'Single Arm Dumbbell Snatch', category: 'gym', difficulty: 'intermediate', equipment: ['Dumbbell'], muscleGroups: ['Full Body', 'Power'], caloriesPerMinute: 10, description: 'Explosive single arm movement', instructions: ['Dumbbell between feet', 'Explosive pull', 'Catch overhead', 'Lower with control'], tips: ['Very explosive', 'Full extension', 'Both sides'], sets: 4, reps: '6-8 each arm' },
  { id: 'ex185', name: 'Renegade Rows', category: 'home', difficulty: 'intermediate', equipment: ['Dumbbells'], muscleGroups: ['Back', 'Core'], caloriesPerMinute: 7, description: 'Plank row combination', instructions: ['Plank position on dumbbells', 'Row one dumbbell', 'Keep hips stable', 'Alternate arms'], tips: ['Don\'t rotate hips', 'Engage core', 'Challenging'], sets: 3, reps: '8-10 each arm' },

  // UNCONVENTIONAL/FUN
  { id: 'ex186', name: 'Bear Crawl to Crab Walk', category: 'home', difficulty: 'intermediate', equipment: [], muscleGroups: ['Full Body'], caloriesPerMinute: 9, description: 'Animal movement flow', instructions: ['Bear crawl forward', 'Transition to crab walk', 'Walk backward', 'Continue alternating'], tips: ['Great warm-up', 'Full body engagement', 'Fun movement'], sets: 3, reps: '30 seconds each' },
  { id: 'ex187', name: 'Monkey Hangs', category: 'home', difficulty: 'beginner', equipment: ['Monkey Bars'], muscleGroups: ['Grip', 'Shoulders'], caloriesPerMinute: 4, description: 'Playground grip strength', instructions: ['Hang from bars', 'Swing hand to hand', 'Traverse across', 'Build grip endurance'], tips: ['Playground workout', 'Grip strength', 'Fun exercise'], duration: 120 },
  { id: 'ex188', name: 'Sandbag Carries', category: 'strength', difficulty: 'intermediate', equipment: ['Sandbag'], muscleGroups: ['Full Body', 'Grip'], caloriesPerMinute: 8, description: 'Loaded carry variation', instructions: ['Lift sandbag', 'Various carry positions', 'Walk for distance', 'Unstable load'], tips: ['Shifting weight', 'Grip challenge', 'Functional strength'], duration: 180 },
  { id: 'ex189', name: 'Sandbag Over Shoulder', category: 'strength', difficulty: 'intermediate', equipment: ['Sandbag'], muscleGroups: ['Full Body', 'Power'], caloriesPerMinute: 10, description: 'Power and conditioning', instructions: ['Sandbag on ground', 'Clean and press over shoulder', 'Drop to other side', 'Alternate'], tips: ['Explosive movement', 'Functional power', 'Both sides'], sets: 4, reps: '8-10' },
  { id: 'ex190', name: 'Wheelbarrow Walks', category: 'home', difficulty: 'beginner', equipment: ['Partner'], muscleGroups: ['Shoulders', 'Core'], caloriesPerMinute: 6, description: 'Partner exercise', instructions: ['Partner holds legs', 'Walk on hands', 'Keep body straight', 'Work together'], tips: ['Fun partner workout', 'Core and shoulder work', 'Communication'], duration: 60 },

  // SPECIFIC SPORT CONDITIONING
  { id: 'ex191', name: 'Basketball Suicides', category: 'sports', difficulty: 'intermediate', equipment: ['Court'], muscleGroups: ['Legs', 'Cardio'], caloriesPerMinute: 12, description: 'Basketball conditioning drill', instructions: ['Sprint to free throw line and back', 'Half court and back', 'Far free throw and back', 'Full court and back'], tips: ['Touch each line', 'All-out effort', 'Sport-specific'], sets: 5, reps: '1 suicide' },
  { id: 'ex192', name: 'Tennis Footwork Drills', category: 'sports', difficulty: 'intermediate', equipment: ['Court', 'Cones'], muscleGroups: ['Legs', 'Agility'], caloriesPerMinute: 8, description: 'Court movement practice', instructions: ['Set up court patterns', 'Quick direction changes', 'Split steps', 'Recovery steps'], tips: ['Stay on toes', 'Quick feet', 'Sport-specific movement'], duration: 300 },
  { id: 'ex193', name: 'Swimming Drills', category: 'sports', difficulty: 'intermediate', equipment: ['Pool'], muscleGroups: ['Full Body', 'Cardio'], caloriesPerMinute: 10, description: 'Technique-focused swimming', instructions: ['Various drill sets', 'Focus on form', 'Build endurance', 'Interval training'], tips: ['Technique over speed', 'Coach guidance helpful', 'Build gradually'], duration: 600 },
  { id: 'ex194', name: 'Boxing Heavy Bag Rounds', category: 'sports', difficulty: 'intermediate', equipment: ['Heavy Bag'], muscleGroups: ['Full Body', 'Cardio'], caloriesPerMinute: 11, description: 'Boxing conditioning', instructions: ['3-minute rounds', '1-minute rest', 'Mix punches', 'Continuous movement'], tips: ['Keep hands up', 'Move around bag', 'Conditioning focused'], sets: 5, reps: '3 minutes' },
  { id: 'ex195', name: 'Goalkeeper Training', category: 'sports', difficulty: 'intermediate', equipment: ['Goals', 'Balls'], muscleGroups: ['Legs', 'Reaction', 'Full Body'], caloriesPerMinute: 8, description: 'Soccer goalkeeper drills', instructions: ['Diving practice', 'Positioning work', 'Reaction saves', 'Distribution'], tips: ['Sport-specific', 'High intensity bursts', 'Recovery between'], duration: 300 },

  // FINAL ADDITIONS TO REACH 200+
  { id: 'ex196', name: 'Nordic Curls', category: 'gym', difficulty: 'advanced', equipment: ['Partner/Anchor'], muscleGroups: ['Hamstrings'], caloriesPerMinute: 7, description: 'Eccentric hamstring exercise', instructions: ['Kneel with ankles secured', 'Lower torso forward', 'Control descent', 'Push back up with hands if needed'], tips: ['Extremely challenging', 'Eccentric strength', 'Injury prevention'], sets: 3, reps: '5-8' },
  { id: 'ex197', name: 'Copenhagen Plank', category: 'home', difficulty: 'advanced', equipment: ['Bench'], muscleGroups: ['Adductors', 'Core'], caloriesPerMinute: 6, description: 'Adductor strengthening', instructions: ['Side plank on elbow', 'Top leg on bench', 'Bottom leg raised', 'Hold position'], tips: ['Very challenging', 'Groin strength', 'Build gradually'], duration: 30 },
  { id: 'ex198', name: 'Sissy Squats', category: 'home', difficulty: 'advanced', equipment: [], muscleGroups: ['Quads'], caloriesPerMinute: 6, description: 'Quad isolation exercise', instructions: ['Lean back while squatting', 'Knees forward', 'Lower down', 'Use support if needed'], tips: ['Very challenging for quads', 'Knee-friendly form', 'Build gradually'], sets: 3, reps: '8-12' },
  { id: 'ex199', name: 'Cossack Squats', category: 'home', difficulty: 'intermediate', equipment: [], muscleGroups: ['Legs', 'Hips', 'Mobility'], caloriesPerMinute: 6, description: 'Lateral squat movement', instructions: ['Wide stance', 'Shift weight to one side', 'Squat on that leg', 'Other leg straight', 'Alternate'], tips: ['Great for mobility', 'Hip flexibility', 'Balance work'], sets: 3, reps: '10-12 each side' },
  { id: 'ex200', name: 'Jefferson Curls', category: 'flexibility', difficulty: 'intermediate', equipment: ['Light Weight'], muscleGroups: ['Back', 'Hamstrings'], caloriesPerMinute: 3, description: 'Loaded flexibility exercise', instructions: ['Hold light weight', 'Slowly curl down vertebra by vertebra', 'Reach toward toes', 'Curl back up'], tips: ['Very light weight', 'Spinal flexibility', 'Controversial - use caution'], sets: 3, reps: '8-10' },
];

// Helper functions
export const getExercisesByCategory = (category: Exercise['category']) => {
  return exerciseLibrary.filter(ex => ex.category === category);
};

export const getExercisesByDifficulty = (difficulty: Exercise['difficulty']) => {
  return exerciseLibrary.filter(ex => ex.difficulty === difficulty);
};

export const searchExercises = (query: string) => {
  const lowerQuery = query.toLowerCase();
  return exerciseLibrary.filter(ex => 
    ex.name.toLowerCase().includes(lowerQuery) ||
    ex.description.toLowerCase().includes(lowerQuery) ||
    ex.muscleGroups.some(mg => mg.toLowerCase().includes(lowerQuery))
  );
};

export const getExercisesByMuscleGroup = (muscleGroup: string) => {
  return exerciseLibrary.filter(ex => 
    ex.muscleGroups.some(mg => mg.toLowerCase() === muscleGroup.toLowerCase())
  );
};
